translate `Manual installation` in japanese
biomejs/biome pull request #1013
Opened 2023-12-02 07:27 UTC by chansuke

## Summary

#880

Translate [Manual insallation](https://biomejs.dev/guides/manual-installation/) page in japanese.

## Test Plan

```shell
cd website
pnpm install
pnpm start
```
and checked the page(including link behavior)

2023-12-02 15:05 UTC, nissy-dev reviewed
Thanks! ! left some comments

2023-12-02 15:09 UTC, unvalley commented on website/src/content/docs/ja/guides/manual-installation.mdx
> +言い換えれば、Biomeが `package.json` を持つ唯一の理由であるべきではありません。
```suggestion
もしあなたが Node.js や npm（あるいは他のパッケージマネージャー）を使用してない場合、Biome のスタンドアロンなCLIバイナリを使用できます。
言い換えれば、`package.json` を持たずに Biome を利用できます。
```

2023-12-02 15:10 UTC, unvalley commented on website/src/content/docs/ja/guides/manual-installation.mdx
> +あなたはツールに既に慣れており、インストールや更新が簡単です。
```suggestion
すでにnpmや他のパッケージマネージャーを使用している場合は、パッケージマネージャーを使用することがBiomeの[推奨されるインストール方法](/ja/guides/getting-started#installation)です。
慣れているツールの利用は、インストールや更新を簡単にします。
```

2023-12-02 15:10 UTC, unvalley commented on website/src/content/docs/ja/guides/manual-installation.mdx
> +Biomeを動作させるためには、プラットフォームに適したバイナリを選択する必要があります。次の表が選択の助けになるでしょう。
```suggestion
Biomeを動作させるためには、プラットフォームに適したバイナリを選択する必要があります。次の表を参考にしてください。
```

2023-12-02 15:11 UTC, unvalley commented on website/src/content/docs/ja/guides/manual-installation.mdx
> +これで、 `./biome` を実行することでBiome を使用出来ます。
```suggestion
これで、 `./biome` を実行することでBiome を使用できます。
```

2023-12-02 15:12 UTC, unvalley requested changes
Thank you for translation, I left some suggestions:)

2023-12-02 15:27 UTC, chansuke commented
@unvalley I appreciate your feedback! I'll check that later🙇

2023-12-02 20:53 UTC, chansuke commented
@nissy-dev @unvalley 
Thank you so much for the review :pray:  I've fixed and rebased. Please take a look when you have a time :bow:

2023-12-02 20:55 UTC, chansuke commented on website/src/content/docs/ja/guides/manual-installation.mdx
> +## Biome を Node.js 無しで使用する
I appreciate for your review

2023-12-03 05:02 UTC, unvalley approved these changes

2023-12-03 05:02 UTC, merged