doc(linter): translate linter document to Japanese
biomejs/biome pull request #1082
Opened 2023-12-06 13:43 UTC by Naturalclar

## Summary
#880 

translated linter document to Japanese

## Test Plan

2023-12-07 15:01 UTC, unvalley commented on website/src/content/docs/ja/linter/index.mdx
> +Biomeのlinterはあなたのコードを静的に分析し、頻出するエラーを検出してより自然なコードを書く手助けをします。
```suggestion
Biomeのlinterはあなたのコードを静的に分析し、典型的なエラーを検出して、より自然なコードを書く手助けをします。
```

2023-12-07 15:01 UTC, unvalley commented on website/src/content/docs/ja/linter/index.mdx
> +CLIから以下のコマンドを実行することでエラーを検出を開始できます：
```suggestion
CLIから以下のコマンドを実行することで、エラーを検出できます：
```

2023-12-07 15:06 UTC, unvalley commented on website/src/content/docs/ja/linter/index.mdx
> +
```suggestion
### 安全ではない修正（Unsafe fixes）

安全ではない修正は、プログラムのセマンティクスを変更する可能性があります。そのため、変更を手動でレビューすることをおすすめします。

_安全ではない修正_を適用するには、`--apply-unsafe`を使用します：

```shell
biome check --apply-unsafe ./src
```

```

2023-12-07 15:06 UTC, unvalley commented on website/src/content/docs/ja/linter/index.mdx
> +### 安全な修正
```suggestion
### 安全な修正（Safe fixes）
```

2023-12-07 15:07 UTC, unvalley commented on website/src/content/docs/ja/linter/index.mdx
> +### 安全な修正
This is because we describe `安全ではない修正` means Unsafe fixes below suggestion. So I'd like to add this one for consistency.

2023-12-07 15:09 UTC, unvalley commented on website/src/content/docs/ja/linter/index.mdx
> +抑制コメントは以下の形式で記述します：
```suggestion

特定のコード行に対して、lintルールを無視したい場合があります。
これは、linterが指摘している行の上に抑制コメントを追加することで実現できます。

抑制コメントは、以下の形式で記述します：
```

2023-12-07 15:12 UTC, unvalley commented on website/src/content/docs/ja/linter/index.mdx
> +ルールの値として`"warn"`を追記することで変更が適用されます。例：
```suggestion
ルールの値として`"warn"`を追記することで変更が適用されます。
例：
```

2023-12-07 15:12 UTC, unvalley commented on website/src/content/docs/ja/linter/index.mdx
> +ルールを無効化するには無効にしたい設定の項目に`"off"`という値を追加します。例：
```suggestion
ルールを無効化するには無効にしたい設定の項目に`"off"`という値を追加します。
例：
```

2023-12-07 15:12 UTC, unvalley commented on website/src/content/docs/ja/linter/index.mdx
> +いくつかのルールにはより詳細な設定があります。
```suggestion
いくつかのルールには、より詳細な設定があります。
```

2023-12-07 15:13 UTC, unvalley commented on website/src/content/docs/ja/linter/index.mdx
> +ルールがいくつかのオプションを_受け入れる_場合は、ルールの値を異なる形に整えることでそれらを渡すことができます。
```suggestion
いくつかのルールには、より詳細な設定があります。
ルールがいくつかのオプションを_受け入れる_場合は、ルールの値を異なる形に整えることで、それらを渡すことができます。
```

2023-12-07 15:20 UTC, unvalley requested changes
Thank you for translation, I left some suggestions:)

2023-12-08 00:36 UTC, Naturalclar commented
Thanks for the review! I will apply the fix today.

2023-12-08 04:24 UTC, unvalley approved these changes
Thank you!

2023-12-08 04:25 UTC, merged