translate readme into ja
biomejs/biome pull request #1174
Opened 2023-12-13 13:27 UTC by K-tecchan

## Summary
Translate readme.md to japanese

close #1125 

## Test Plan

2023-12-13 16:48 UTC, unvalley commented on packages/@biomejs/biome/README.ja.md
> +あなたがコードを書いているときに、形の崩れたコードを format と lint することができます。
```suggestion
**Biome** はウェブプロジェクトのための高性能なツールチェーンであり、プロジェクトの健全性を維持するための開発者ツールの提供を目的としています。

**Biome は _JavaScript_, _TypeScript_, _JSX_ そして _JSON_ 向けの[高速なFormatter](./benchmark#formatting)**であり、**[_Prettier_ との互換性は96%](https://console.algora.io/challenges/prettier)** を達成しています。

**Biome は _JavaScript_, _TypeScript_, _JSX_ のための[高性能なLinter](https://github.com/biomejs/biome/tree/main/benchmark#linting)** であり、ESLint, TypeScript ESLint, [その他のソース](https://github.com/biomejs/biome/discussions/3)から **[170以上のルール](https://biomejs.dev/linter/rules/)**を提供しています。Biome は**詳細で文脈に沿った結果を出力**するため、コードを改善し、より良いプログラマになるための手助けをします！

**Biome** は最初から[**エディタ内で対話的に**](https://biomejs.dev/ja/guides/integrate-in-editor/)使用できるように設計されています。
あなたがコードを書いているときに、形の崩れたコードを format と lint することができます。
```

2023-12-13 16:57 UTC, unvalley commented on packages/@biomejs/biome/README.ja.md
> +**Biome** はソーステキストを完全に表現し、最高のエラー回復を提供する洗練されたパーサーを持つ、最高級の LSP サポートを提供します。
```suggestion
Biomeは、ソーステキストの完全な表現力とエラー回復能力を持つ洗練されたParserによって、優れたLSPサポートを提供します。
```

2023-12-13 16:58 UTC, unvalley commented on packages/@biomejs/biome/README.ja.md
> +**Biome** は以前は別々のツールだった機能を統合します。共通基盤を構築することで、コードの処理、エラーの表示、並列処理、キャッシュ、設定について統一的な体験を提供することができます。
```suggestion
**Biome** は、以前は別々のツールで提供されている機能を統合します。共通基盤を構築することで、コードの処理、エラーの表示、並列処理、キャッシュ、設定について統一的な体験を提供します。
```

2023-12-13 17:00 UTC, unvalley commented on packages/@biomejs/biome/README.ja.md
> +私たちの[プロジェクトの哲学][biome-philosophy]について詳しく読んでください。
```suggestion
興味のある方は、[プロジェクトの理念][biome-philosophy]もご覧ください。
```

2023-12-13 17:02 UTC, unvalley commented on packages/@biomejs/biome/README.ja.md
> +npx @biomejs/biome ci ./src
```suggestion
# CI環境では、すべてのファイルを対象にformatやlintをチェックする
npx @biomejs/biome ci ./src
```

2023-12-13 17:03 UTC, unvalley requested changes
Thank you for translation, I left some suggestions!

2023-12-14 01:18 UTC, ImBIOS commented
I recommend for translation links, don't use inline links like this: [lang a](url) | [lang b](url) | [lang c](url)

It's prone to merge conflict if in the future we need to translate into different languages at the same time.

I suggest to use  one line per language:

- [lang a](url)
- [lang b](url)
- [lang c](url)

In this way, diff for each line counted as different work, so the probability of merge conflict would be less.

2023-12-14 07:43 UTC, ematipico commented
Thank you @ImBIOS , do you agree with me that what you suggested can be done in a different pr?

If you do, would you like to send a PR for fixing that?

2023-12-14 08:41 UTC, ImBIOS commented
@ematipico I ultimately agree, let me hunt down this 👾 minion task, 🚚  I'll PR to this branch.

2023-12-15 14:22 UTC, unvalley commented on packages/@biomejs/biome/README.ja.md
> +**Biome** は、以前は別々のツールで提供されていた機能を統合します。共通基盤を構築することで、コードの処理、エラーの表示、並列処理、キャッシュ、設定について統一的な体験を提供します。
```suggestion
**Biome** は以前は別々のツールで提供されていた機能を統合します。共通基盤を構築することで、コードの処理、エラーの表示、並列処理、キャッシュ、設定について統一的な体験を提供します。
```

2023-12-15 17:46 UTC, unvalley commented on packages/@biomejs/biome/README.ja.md
> +**Biome** はウェブプロジェクトのための高性能なツールチェーンであり、プロジェクトの健全性を維持するための開発者ツールの提供を目的としています。
```suggestion
**Biome** はWebプロジェクトのための高性能なツールチェーンであり、プロジェクトの健全性を維持するための開発者ツールの提供を目的としています。
```

2023-12-15 18:04 UTC, unvalley approved these changes
I've changed a bit, and it looks good for me.

2023-12-15 18:04 UTC, merged

2023-12-16 04:12 UTC, K-tecchan commented
thanks!