docs: translate `README.md` to `pt-br`
biomejs/biome pull request #1211
Opened 2023-12-16 02:20 UTC by ImBIOS

## Summary

## Test Plan

2023-12-16 19:48 UTC, danielsarsi reviewed
Leaving my suggestions here.

2023-12-16 19:48 UTC, danielsarsi commented on packages/@biomejs/biome/README.pt-br.md
> +[![CI na principal][ci-badge]][ci-url]
Maybe should be "CI na `main`"?
```suggestion
[![CI na `main`][ci-badge]][ci-url]
```

2023-12-16 19:48 UTC, danielsarsi commented on packages/@biomejs/biome/README.pt-br.md
> +**Biome é um [linteiro eficiente](https://github.com/biomejs/biome/tree/main/benchmark#linting)** para _JavaScript_, _TypeScript_, e _JSX_ que possui **[mais de 170 regras](https://biomejs.dev/linter
I suggest using "linter", as "linteiro" is an foreignism.
```suggestion
**Biome é um [linter eficiente](https://github.com/biomejs/biome/tree/main/benchmark#linting)** para _JavaScript_, _TypeScript_, e _JSX_ que possui **[mais de 170 regras](https://biomejs.dev/linter/rules/)** do ESLint, TypeScript ESLint, e de [outras fontes](https://github.com/biomejs/biome/discussions/3).
```

2023-12-16 19:48 UTC, danielsarsi commented on packages/@biomejs/biome/README.pt-br.md
> +ou vá diretamente para o [Guia de Introdução][getting-started] para começar a usar o Biome.
```suggestion
ou vá ao [Guia de Introdução][getting-started] para começar a usar o Biome.
```

2023-12-16 19:48 UTC, danielsarsi commented on packages/@biomejs/biome/README.pt-br.md
> +**Biome** é uma cadeia de ferramentas de alto desempenho para projetos web, visando fornecer ferramentas de desenvolvimento para manter a saúde desses projetos.
```suggestion
**Biome** é um conjunto de ferramentas de alto desempenho para projetos web, visando fornecer recursos de desenvolvimento para manter a saúde desses projetos.
```

2023-12-16 23:08 UTC, CookieDasora reviewed
Thanks @ImBIOS for your contribution, I left some suggestions.

2023-12-16 23:08 UTC, CookieDasora commented on packages/@biomejs/biome/README.pt-br.md
> +Pode formatar e lintar código malformado enquanto você está escrevendo.
"Isso permite formatar e lintar códigos malformados enquanto você programa."

2023-12-17 02:03 UTC, ImBIOS commented
Thanks for the feedback. Very helpful for me.

2023-12-17 11:14 UTC, unvalley requested changes
Thank you for translation!
I can't review Brazilian Portuguese language, thank you for reviewers! 
We can merge this after fixing my request.

2023-12-17 11:14 UTC, unvalley commented on packages/@biomejs/biome/README.ja.md
> -[getting-started]: https://biomejs.dev/ja/guides/getting-started/
This line is needed to link, but bench can be deleted because it's unused.

2023-12-17 12:29 UTC, victor-teles requested changes

2023-12-17 12:29 UTC, victor-teles commented on packages/@biomejs/biome/README.pt-br.md
> +    <img alt="Biome - Cadeia de ferramentas da web"
```suggestion
    <img alt="Biome - Conjunto de ferramentas da web"
```
Previously we translated this into "Conjunto de ferramentas", so would be good to keep the same here

2023-12-17 13:55 UTC, danielsarsi approved these changes
Seems good to me!

2023-12-18 01:06 UTC, unvalley approved these changes

2023-12-18 01:13 UTC, victor-teles approved these changes

2023-12-18 01:13 UTC, merged