docs(tr): Add Turkish language support
biomejs/biome pull request #1227
Opened 2023-12-17 03:42 UTC by ImBIOS

## Summary

## Test Plan

2023-12-17 08:04 UTC, ematipico commented
Hey @ImBIOS, I noticed you opened a bunch of PRs for translating content in other languages:
- do you speak all those languages?
- do you know someone that is going to help us with all these translations?

2023-12-17 10:21 UTC, ImBIOS commented
@ematipico I don't daily speak all those languages, I just love to learn multiple languages, but I'm committed to ensuring those translations are accurate and high-quality. I've already reached out to some native speakers who can assist with these translations. My goal is to make our content accessible to a wider audience, and I believe it's a valuable effort.

I'm coordinating with these individuals to ensure that the translations are not just linguistically correct, but also culturally relevant and technically accurate. I'm taking this seriously to maintain the integrity and quality of the content.

2023-12-19 01:25 UTC, anonrig requested changes

2023-12-19 01:25 UTC, anonrig commented on packages/@biomejs/biome/README.tr.md
> +**Biome, _JavaScript_, _TypeScript_, _JSX_ ve _JSON_ için [hızlı bir formatlayıcıdır](./benchmark#formatting)** ve **[_Prettier_ ile %96 uyumluluk](https://console.algora.io/challenges/prettier)** pu
```suggestion
**Biome, _JavaScript_, _TypeScript_, _JSX_ ve _JSON_ için [hızlı bir formatlayıcıdır](./benchmark#formatting)** ve **[_Prettier_ ile %96 uyumludur](https://console.algora.io/challenges/prettier)**.
```

2023-12-19 01:25 UTC, anonrig commented on packages/@biomejs/biome/README.tr.md
> +**Biome, _JavaScript_, _TypeScript_ ve _JSX_ için [performanslı bir lintleyicidir](https://github.com/biomejs/biome/tree/main/benchmark#linting)** ve ESLint, TypeScript ESLint ve [diğer kaynaklardan]
```suggestion
**Biome, _JavaScript_, _TypeScript_ ve _JSX_ için [performanslı bir derleyicidir](https://github.com/biomejs/biome/tree/main/benchmark#linting)** ve ESLint, TypeScript ESLint ve [diğer kaynaklardan](https://github.com/biomejs/biome/discussions/3) **170'den fazla kural** içerir.
```

2023-12-19 01:25 UTC, anonrig commented on packages/@biomejs/biome/README.tr.md
> +Yazarken hatalı kodu formatlayabilir ve lintleyebilir.
```suggestion
Yazarken hatalı kodu formatlayabilir ve lintleyebilirsiniz.
```

2023-12-19 01:25 UTC, anonrig commented on packages/@biomejs/biome/README.tr.md
> +Biome'u yüklemek istemeden denemek istiyorsanız, WebAssembly'ye derlenmiş [çevrimiçi oyun alanını](https://biomejs.dev/playground/) kullanın.
```suggestion
Biome'u yüklemek istemeden denemek istiyorsanız, WebAssembly'ye derlenmiş [oyun alanını](https://biomejs.dev/playground/) kullanabilirsiniz.
```

2023-12-19 01:25 UTC, anonrig commented on packages/@biomejs/biome/README.tr.md
> +akkında Daha Fazlası
```suggestion
## Biome Hakkında Daha Fazlası
```

2023-12-19 01:25 UTC, anonrig commented on packages/@biomejs/biome/README.tr.md
> +**Biome**, modern web geliştirmenin [tüm ana dillerini][language-support] desteklemeyi amaçlar.
```suggestion
**Biome**, modern web geliştirmenin [tüm dillerini][language-support] desteklemeyi amaçlar.
```

2023-12-19 01:25 UTC, anonrig commented on website/astro.config.ts
> +								tr: "Başlarken",
```suggestion
								tr: "Başla",
```

2023-12-19 01:25 UTC, anonrig commented on website/astro.config.ts
> +								tr: "El ile kurulum",
```suggestion
								tr: "Kurulum kılavuzu",
```

2023-12-19 01:25 UTC, anonrig commented on website/astro.config.ts
> +								tr: "Büyük projelerde Biome kullanma",
```suggestion
								tr: "Büyük projelerde Biome",
```

2023-12-19 01:25 UTC, anonrig commented on website/astro.config.ts
> +								tr: "Biome'u editörünüze entegre edin",
```suggestion
								tr: "Biome'u editörünüze ekleyin",
```

2023-12-19 01:25 UTC, anonrig commented on website/astro.config.ts
> +								tr: "Analizör",
```suggestion
								tr: "İnceleyici",
```

2023-12-19 01:25 UTC, anonrig commented on website/astro.config.ts
> +										tr: "Prettier ile farklılıklar",
```suggestion
										tr: "Prettier arasındaki farklar",
```

2023-12-19 01:25 UTC, anonrig commented on website/astro.config.ts
> +										tr: "Biçimlendirici seçenek felsefesi",
```suggestion
										tr: "Biçimlendirici prensipleri",
```

2023-12-19 01:25 UTC, anonrig commented on website/astro.config.ts
> +						tr: "Referans",
```suggestion
						tr: "Referanslar",
```

2023-12-19 01:25 UTC, anonrig commented on website/astro.config.ts
> +								tr: "VSCode uzantısı",
```suggestion
								tr: "VSCode eklentisi",
```

2023-12-19 01:27 UTC, anonrig commented
> @ematipico I don't daily speak all those languages, I just love to learn multiple languages, but I'm committed to ensuring those translations are accurate and high-quality. I've already reached out to some native speakers who can assist with these translations. My goal is to make our content accessible to a wider audience, and I believe it's a valuable effort.
> 
> I'm coordinating with these individuals to ensure that the translations are not just linguistically correct, but also culturally relevant and technically accurate. I'm taking this seriously to maintain the integrity and quality of the content.

I gave up after a while but they are not exact translations. It feels "artificial" when you read it. (PS: I'm Turkish and speak/write Turkish fluently)

2023-12-19 02:03 UTC, ImBIOS commented
@anonrig Thanks for your review, it's a great experience for me to learn along the way.

2023-12-22 11:37 UTC, ematipico commented
> > @ematipico I don't daily speak all those languages, I just love to learn multiple languages, but I'm committed to ensuring those translations are accurate and high-quality. I've already reached out to some native speakers who can assist with these translations. My goal is to make our content accessible to a wider audience, and I believe it's a valuable effort.
> > I'm coordinating with these individuals to ensure that the translations are not just linguistically correct, but also culturally relevant and technically accurate. I'm taking this seriously to maintain the integrity and quality of the content.
> 
> I gave up after a while but they are not exact translations. It feels "artificial" when you read it. (PS: I'm Turkish and speak/write Turkish fluently)

Yeah, that's what I thought at the beginning, I think all these translations are translated using Google Translate and/or some AI tool.

Sorry @anonrig taking so much of your time. @ImBIOS, this is not the approach we want to take for translating our documentation. Unless you speak those languages, we don't want to use automated tools, because the majority of the work falls on the reviewer, not the creator.

2023-12-22 11:37 UTC, closed without merging