website: Hero community section
biomejs/biome pull request #1279
Opened 2023-12-21 12:24 UTC by vasucp1207

## Summary

## Test Plan

2023-12-21 12:34 UTC, ematipico commented
@vasucp1207 I wish you would start filling out the PR template. Many contributors - even first-time contributors - make the effort to provide some information. Could you please do the same?

2023-12-22 11:19 UTC, ematipico commented
Thank you @vasucp1207 ! 

This is an amazing addition to our homepage. 

> The community section currently feels a bit empty to me(left side of the section and on small screens) as of now, any suggestions on how we could do this better, or is it okay?

I think it's OK! However, I think we should show the Github avatars on tablets and mobile phones too, and maybe we can blur them if they happen to go under the buttons. Check how the Astro website does it. This way, it doesn't feel empty anymore.

Here's more feedback: 
- I am not sure what "Powered by Astro" means here. Do you mean that the **website** is powered by Astro? If so, I don't think we should mention it. Maybe just saying "Powered by our open source contributors" should be enough 
- I think we should change how we fetch and show the GitHub avatars. On this page, I think we should sort the contributors by their number of contributors (very much like the order of contributors you see here: https://github.com/biomejs/biome/graphs/contributors), and render them **statically**, so we don't ship any additional JavaScript in the homepage. 
- I noticed that the homepage downloads a component that we don't use in the homepage. Could you check why? Maybe I am wrong and we do use it somewhere
![Screenshot 2023-12-22 at 11 17 36](https://github.com/biomejs/biome/assets/602478/4574f170-49a8-4590-8097-59f58dcabe20)

2023-12-22 13:39 UTC, victor-teles requested changes

2023-12-22 13:39 UTC, victor-teles commented on website/src/frontend-scripts/contributors.ts
> +const applyStyles = (element: any, styles: any) => {
Seems this code is not properly formatted, you can format it using `pnpm format`

2023-12-22 13:39 UTC, victor-teles commented on website/src/components/Community.astro
> +  <div class="community-head">Community</div>
The contrast ratio for this title and the description seems a little bit lower, you should keep some similarity to "Biome is fast" title

2023-12-22 13:39 UTC, victor-teles commented on website/src/components/Community.astro
> +        <Icon name="discord" /> Discord
This links are missing the `href`

2023-12-22 13:46 UTC, victor-teles commented
IMO this should also be available in other languages, even in English.
Any thoughts?

By the way, the way the component was made make translation a bit hard
@vasucp1207 Maybe you need to rethink how to support the translation to this component

2023-12-23 16:40 UTC, vasucp1207 commented
> * I noticed that the homepage downloads a component that we don't use in the homepage. Could you check why? Maybe I am wrong and we do use it somewhere
>   ![Screenshot 2023-12-22 at 11 17 36](https://private-user-images.githubusercontent.com/602478/292474921-4574f170-49a8-4590-8097-59f58dcabe20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNDk4NzAsIm5iZiI6MTcwMzM0OTU3MCwicGF0aCI6Ii82MDI0NzgvMjkyNDc0OTIxLTQ1NzRmMTcwLTQ5YTgtNDU5MC04MDk3LTU5ZjU4ZGNhYmUyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QxNjM5MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTE4YmFlNWVjMTllZTQ0YjM1YTNhODhlZGE4ZjQwZDkxYjdjYTcyZGVmNjFkOGQyMjU3NmE2ZjM3NjcwMWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T1M6mCyJAmjGNR5kkPoYI4bvyPhCXZiSeAbJ51jnWlE)

This also downloads in Starlight and Astro docs.

2023-12-23 17:24 UTC, ematipico commented
Good to know, it could be a bug

2023-12-24 07:14 UTC, ematipico commented
I found two problems:
- the avatars are incorrectly placed
- the performance banner doesn't have the same padding of the cards 

![IMG_20231224_071218.jpg](https://github.com/biomejs/biome/assets/602478/c2366646-12b7-4600-9e1d-0ea44aa5f0b4)

![IMG_20231224_071155.jpg](https://github.com/biomejs/biome/assets/602478/45c32946-cb2b-4dc0-89a8-854358bc7f18)

2023-12-24 07:22 UTC, unvalley commented on website/src/content/docs/index.mdx
>  <div class="sponsors">
`<h2 class="sponsor-head">Sponsors</h2>` should be  in `<div class="sponsors">`

2023-12-24 07:23 UTC, unvalley commented on website/src/content/docs/ja/index.mdx
> +    alt: Biome，Web 工具链
use Japanese correctly
```suggestion
    alt: Biome, ウェブツールチェイン
```

2023-12-24 07:25 UTC, unvalley commented on website/public/img/site.webmanifest
We don't need this file?

2023-12-24 07:36 UTC, unvalley commented on website/src/content/docs/index.mdx
> +    <h2 class="head">Biome is fast</h2>
Picked this up from Rome's one.
```suggestion
    <h2 class="supercharge-head">Supercharge your workflow</h2>
    <p class="supercharge-description">Experience the seamless integration of a vertical toolchain. Full of useful features like formatting and linting, with even more in the future.</p>
```

2023-12-24 07:40 UTC, unvalley commented
Thank you for your contribution. Overall I'd like to take over the Rome's web page. Adding contributors section is good.
Sorry for the poor explanation, but I want to take care of the margins.

2023-12-24 08:07 UTC, unvalley commented on website/src/playground/components/Progress.tsx
The end of the progress should arrive at the right end. With the current progress bar, it is difficult to visually recognize Biome as fast. I attached Rome's one.
![Screenshot 2023-12-24 at 17 03 54](https://github.com/biomejs/biome/assets/38400669/4996dba8-3ce6-4963-a2f3-ebe8068b6228)

2023-12-24 11:23 UTC, ematipico commented
@vasucp1207 

I resolved a bunch of conflicts and made a few changes. Regarding the avatars, I removed the style that hides contributors' avatars. I believe it's best to create predefined roles with a predefined number of elements per row, and we should not use CSS to hide the avatars.

2023-12-24 14:34 UTC, vasucp1207 commented
> Thank you for your contribution. Overall I'd like to take over the [Rome's web page](https://web.archive.org/web/20230203060333/https://rome.tools/). Adding contributors section is good. Sorry for the poor explanation, but I want to take care of the margins.

Feel free to make any changes

2023-12-25 10:59 UTC, ematipico commented
@vasucp1207 

That's what I see on iPad
![Screen Shot 2023-12-25 at 10 58 35](https://github.com/biomejs/biome/assets/602478/fc17b104-e828-4b73-a4ef-e334d741d97b)

2023-12-28 13:28 UTC, ematipico commented
hey @victor-teles , I am going to merge this PR. It would be best to propose something about the translations.

I checked your comment and it wasn't very actionable. It seems you know what you want, but even I couldn't understand your suggestion.

2023-12-28 13:28 UTC, merged