docs(pt-br): translated git hooks page
biomejs/biome pull request #1498
Opened 2024-01-09 19:33 UTC by CookieDasora

## Summary

This PR adds the Portuguese translation of the Git Hooks guide as requested in #1421, adds the new homepage to portuguese version of the website and translates the guide Integrate in VCS.

## Test Plan

- Check if there is no missing translation in the translated files.
- Check if the translations are correct and if they adhere to the grammatical rules of Portuguese.

2024-01-10 22:44 UTC, victor-teles requested changes

2024-01-10 22:44 UTC, victor-teles commented on website/src/content/docs/pt-br/guides/integrate-in-vcs.mdx
> +Essa configuração não faz **qualquer coisa em si**. Você precisa adicionar novos recursos.
```suggestion
Essa configuração não faz **nada por si só**. Você precisa adicionar novos recursos.
```

What do you think?

2024-01-10 22:44 UTC, victor-teles commented on website/src/content/docs/pt-br/guides/integrate-in-vcs.mdx
> +Isso é um recurso que permite que o Biome leia os arquivos ignorados do VCS e ignora todos os arquivos e pastas especificados nele. Esse é um recurso opcional, e você precisa ativar o campo `vcs.useI
```suggestion
Esse é um recurso que permite que o Biome leia os arquivos ignorados do VCS e ignora todos os arquivos e pastas especificados nele. Esse é um recurso opcional, e você precisa ativar o campo `vcs.useIgnoreFile`:
```
To keep same as "Processando apenas arquivos modificados"

2024-01-11 11:29 UTC, CookieDasora commented on website/src/content/docs/pt-br/guides/integrate-in-vcs.mdx
> +Essa configuração não faz **qualquer coisa em si**. Você precisa adicionar novos recursos.
Sounds good!

2024-01-12 14:24 UTC, victor-teles approved these changes
Looks good to me

2024-01-12 18:06 UTC, merged