docs(website): add git-hook Japanese translation
biomejs/biome pull request #1503
Opened 2024-01-10 08:04 UTC by OldBigBuddha

## Summary

Translate [git-hooks](https://biomejs.dev/recipes/git-hooks/) into Japanese

related to #1421

## Test Plan

N/A

2024-01-10 14:55 UTC, unvalley commented
Okay, I'll check

2024-01-10 14:59 UTC, unvalley commented on website/src/content/docs/ja/recipes/git-hooks.mdx
> +  ```
I think this code block is broken. The original does too, so we need to fix it.

2024-01-10 15:00 UTC, unvalley commented on website/src/content/docs/ja/recipes/git-hooks.mdx
> +- コミットをする前にformatチェックやlintを行い、[安全な修正](../linter#安全な修正safe-fixes)を行う
```suggestion
- コミット前にformatチェックやlintを行い、[安全な修正](../linter#安全な修正safe-fixes)を行う
```

2024-01-10 15:00 UTC, unvalley commented on website/src/content/docs/ja/recipes/git-hooks.mdx
> +- プッシュする前にformatのチェックとlintを行う
```suggestion
- プッシュ前にformatとlintのチェックを行う
```

2024-01-10 15:02 UTC, unvalley commented on website/src/content/docs/ja/recipes/git-hooks.mdx
> +どのファイルをBiomeの対象にするかをもっとコントロールしたい場合は `glob` を使ってください。
```suggestion
`--files-ignore-unknown=true` を指定するだけで、Biomeが現在サポートしている（もしくは将来サポートするかもしれない）ファイルのみを対象にできます。
対象ファイルをさらにコントロールしたい場合は、`glob` を使ってください。
```

2024-01-10 15:02 UTC, unvalley commented on website/src/content/docs/ja/recipes/git-hooks.mdx
> +設定したら、`lefthook install` を実行してフックのセットアップを完了させましょう。
```suggestion
設定後、`lefthook install` を実行してフックのセットアップを完了させましょう。
```

2024-01-10 15:03 UTC, unvalley commented on website/src/content/docs/ja/recipes/git-hooks.mdx
> +パッケージのインストール時に `scripts.postinstall` を使って自動的に _Lefthook_ のフックを設定することができます：
```suggestion
プロジェクトに `package.json` が含まれている場合、パッケージのインストール時に `scripts.postinstall` を使って自動的に _Lefthook_ のフックを設定することができます：
```

2024-01-10 15:03 UTC, unvalley commented on website/src/content/docs/ja/recipes/git-hooks.mdx
> +Husky はステージングされていない変更を無視したり、ステージングされているファイルののみを対象とすることができません。
```suggestion
Husky はステージングされていない変更を無視したり、ステージングされているファイルのみを対象としたりすることができません。
```

2024-01-10 15:03 UTC, unvalley commented on website/src/content/docs/ja/recipes/git-hooks.mdx
> +`scripts.postinstall` を使ってパッケージのインストール時に自動的に _husky_ のフックを設定することができます：
```suggestion
プロジェクトに `package.json` が含まれている場合、`scripts.postinstall` を使ってパッケージのインストール時に自動的に _husky_ のフックを設定することができます：
```

2024-01-10 15:04 UTC, unvalley commented on website/src/content/docs/ja/recipes/git-hooks.mdx
> +詳しくは [_git-format-staged_ と他のツールの比較](https://github.com/hallettj/git-format-staged#comparisons-to-similar-utilities) を参照してください。
```suggestion
_lefthook_、_pre-commit_、_lint-staged_ などの他のツールとは対照的に、[git-format-staged](https://github.com/hallettj/git-format-staged) は内部的に `git stash` を使用しません。
これにより、ステージングされていない変更とステージングされた変更の間で衝突が発生した場合に、手動で介入する必要がなくなります。
詳しくは [_git-format-staged_ と他のツールの比較](https://github.com/hallettj/git-format-staged#comparisons-to-similar-utilities) を参照してください。
```

2024-01-10 15:05 UTC, unvalley commented on website/src/content/docs/ja/recipes/git-hooks.mdx
> +- コミットをする前にformatのチェックとlintを行う
```suggestion
- コミット前にformatとlintのチェックを行う
```

2024-01-10 15:05 UTC, unvalley commented on website/src/content/docs/ja/recipes/git-hooks.mdx
> +- コミットをする前にformatチェックやlint、安全な修正を行う
```suggestion
- コミット前にformatやlintのチェック・安全な修正を行う
```

2024-01-10 15:06 UTC, unvalley commented on website/src/content/docs/ja/recipes/git-hooks.mdx
> +[pre-commit](https://pre-commit.com/)は多言語フックマネージャーです。
```suggestion
[pre-commit](https://pre-commit.com/)は、多言語フックマネージャーです。
```

2024-01-10 15:07 UTC, unvalley commented on website/src/content/docs/ja/recipes/git-hooks.mdx
> +なので `additional_dependencies` オプションを使ってBiomeのバージョンを指定しなくてはいけません。
```suggestion
[pre-commit](https://pre-commit.com/)は別々にツールをインストールするため、pre-commit はどのツールがインストールされるか知っておく必要があります。
そのため、`additional_dependencies` オプションを使ってBiomeのバージョンを指定しなくてはいけません。
```

2024-01-10 15:08 UTC, unvalley commented on website/src/content/docs/ja/recipes/git-hooks.mdx
> +提供されているBiomeフックを使う代わりに、独自の[ローカルフック](https://pre-commit.com/index.html#repository-local-hooks)を指定することができます。
```suggestion
Biome がすでに `npm` のパッケージとしてローカルリポジトリにインストールされている場合、Biome を更新する際に `package.json` と `.pre-commit-config.yaml` の両方を更新するのは開発者の負担になります。
提供されているBiomeフックを使う代わりに、独自の[ローカルフック](https://pre-commit.com/index.html#repository-local-hooks)を指定できます。
```

2024-01-10 15:08 UTC, unvalley commented on website/src/content/docs/ja/recipes/git-hooks.mdx
> +pre-commit の `files` オプションは必須ではありません。
```suggestion
Biome は`--files-ignore-unknown=true`を指定することで未知のファイルを無視するため、pre-commit の `files` オプションは必須ではありません。
```

2024-01-10 15:09 UTC, unvalley commented on website/src/content/docs/ja/recipes/git-hooks.mdx
> +- コミットをする前にformatのチェックとlintを行う
```suggestion
- コミット前にformatとlintのチェックを行う
```

2024-01-10 15:09 UTC, unvalley commented on website/src/content/docs/ja/recipes/git-hooks.mdx
> +- コミットをする前にformatチェックやlint、安全な修正を行う
```suggestion
- コミット前にformatやlintのチェック、安全な修正を行う
```

2024-01-10 15:09 UTC, unvalley commented on website/src/content/docs/ja/recipes/git-hooks.mdx
> +すでにステージングされたファイルに新たな変更がある場合はフックを失敗させていることに注意してください。
```suggestion
すでにステージングされたファイルに新たな変更がある場合は、フックを失敗させていることに注意してください。
```

2024-01-10 15:10 UTC, unvalley requested changes
Thank you for contribution! I left some minor suggestions.

2024-01-11 15:59 UTC, OldBigBuddha commented
@unvalley I appreciate your reviews. I applied all your suggestions!
Please check it again 🙏

2024-01-11 16:06 UTC, unvalley commented
@OldBigBuddha Thank you, looks good to me!

2024-01-11 16:14 UTC, unvalley approved these changes

2024-01-11 23:07 UTC, merged