Implement format option singleAttributePerLine
biomejs/biome pull request #1712
Opened 2024-01-30 20:17 UTC by octoshikari

## Summary
I've added implementation for prettier option single Attribute Per Line that was added b prettier 2.6.0 version. This option last that we need in our projects to migrate from eslint to biome

[Issue link](https://github.com/biomejs/biome/issues/1706)

## Test Plan
I've add new test cases that apply this rule

2024-01-31 15:27 UTC, tylerlaprade commented
>This option last that we need in our projects to migrate from eslint to biome

To clarify, you mean Prettier here, not ESLint, right? You can separately migrate formatting/linting according to your Biome config, so migration from ESLint should not be blocked by this.

2024-01-31 15:34 UTC, octoshikari commented
@tylerlaprade We don't use prettier, but we have this eslint-plugin-react rule `react/jsx-max-props-per-line` that similar to prettier option and make code more readable. A most easy way to do it, support Prettier option - single Attribute Per Line in biome. As result we want make full switch to biome for linting/formatting approach

2024-01-31 16:56 UTC, denbezrukov commented on crates/biome_js_formatter/src/context.rs
> +    /// Enforce single attribute per line in HTML, Vue and JSX. Defaults to false
I think it's better to remove `HTML` and `Vue` because the option is related only to JSX now.

2024-01-31 17:20 UTC, denbezrukov requested changes
Great PR!
Thank you for your contribution! I believe that you need to accept new snapshots for the CLI to pass the tests and remove HTML and Vue mentions.

One thought I'd like to discuss before merging: since this option is now only for JSX, and we already have a JSX-specific option for quotes (`jsx-single-quote`), I'm wondering if a better name for it might be `jsx-single-attribute-per-line`?

I understand that this differs from a Prettier option.

Any thoughts?

2024-01-31 17:22 UTC, denbezrukov commented
I forgot to mention that we need to implement the option for the playground. We can do it in another PR if it requires many changes.

2024-01-31 17:30 UTC, octoshikari commented
@denbezrukov Strange thing here with snapshots. I'm already updated them and you can see this in changed files, but in workflow job old version used, but i will double check this. 
For me okay  rename option for jsx only. I think this more about Prettier compability , but while biome doesn't support HTML and Vue files we can move option under jsx section, and implement in сommon formatter option after support HTML and Vue.

2024-02-02 21:12 UTC, denbezrukov commented
Hey everyone,

Based on our discussions on discord and polls (https://github.com/biomejs/biome/discussions/1735, https://github.com/biomejs/biome/discussions/1736), we're proposing a new formatter option named `attributePosition`, with two variants:`auto` and  `multi-line`.

### Variants Explained:

`auto`: The formatter tries to fit all attributes on one line; if not possible, each attribute goes on its own line.
`multi-line`: Regardless of space, each attribute is placed on a new line for consistency.

Thanks for helping us shape this feature. Your feedback drives our project's improvement.

Cheers.

2024-02-03 09:45 UTC, denbezrukov requested changes
Great job! One thing we need to do is to update our changelog.

https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md#changelog

2024-02-03 09:45 UTC, denbezrukov commented on crates/biome_js_formatter/src/context.rs
> +pub struct SingleAttributePerLine(bool);
Do we need it?

2024-02-03 09:45 UTC, denbezrukov commented on crates/biome_service/src/configuration/javascript/formatter.rs
> +    /// The attribute position style in JavaScript code. Defaults to auto..
```suggestion
    /// The attribute position style in JavaScript code. Defaults to auto.
```

2024-02-03 09:48 UTC, denbezrukov commented on crates/biome_js_formatter/tests/language.rs
> +    /// Enforce single attribute per line in JSX. Defaults to false
It seems that we need to update the docs here.

2024-02-03 09:58 UTC, octoshikari commented on crates/biome_js_formatter/src/context.rs
> +pub struct SingleAttributePerLine(bool);
I forgot to remove this. 😨

2024-02-03 10:09 UTC, octoshikari commented
@denbezrukov Changelog  and review comments has been fixed

2024-02-03 10:12 UTC, denbezrukov approved these changes
🎉🎉🎉

2024-02-03 11:41 UTC, merged