docs(pt-br): Update pt-br/index.mdx
biomejs/biome pull request #2139
Opened 2024-03-20 11:03 UTC by Exerea

## Summary
Update pt-br homepage.

Related: https://github.com/biomejs/biome/issues/1958

## Test Plan
Run pnpm start locally and check/compare the translated homepage on the dev server with the default one.

2024-03-20 19:39 UTC, victor-teles requested changes

2024-03-20 19:39 UTC, victor-teles commented on website/src/content/docs/pt-br/index.mdx
> +description: Formato, fiapos e muito mais em uma fração de segundo.
@Exerea This change doesn't look good for me (as a native speaker)

2024-03-20 19:39 UTC, victor-teles commented on website/src/content/docs/pt-br/index.mdx
> +      Alimentado por nossos colaboradores de código aberto
@Exerea I think in this case "Mantido" or "Desenvolvido" is more appropriate here

2024-03-20 19:39 UTC, victor-teles commented on website/src/content/docs/pt-br/index.mdx
> +description: Formato, fiapos e muito mais em uma fração de segundo.
Also, you need to keep the same sentence on the site hero section

2024-03-20 19:39 UTC, victor-teles commented on website/src/content/docs/pt-br/index.mdx
> +  title: Cadeia de ferramentas integrada para o desenvolvimento de projetos da Web.
@Exerea You need to keep the same sentence on the site hero section

2024-03-22 13:42 UTC, Exerea commented
@victor-teles  Thank you for your feedback! I have updated it.

2024-03-25 22:00 UTC, victor-teles approved these changes

2024-03-25 22:52 UTC, merged