docs: fix incorrect bullet char + fix links
biomejs/biome pull request #2875
Opened 2024-05-15 21:02 UTC by MacFJA

## Summary

Fix some minor formatting issue with the documentation of the rule

> [!WARNING]
> Be aware that this PR introduce `HardBreak` that a currently not handled by the parser of the website (I have another PR to add this)

This PR is the first part of a permanent solution for this PR: https://github.com/biomejs/website/pull/307 (which will be close and replace)

2024-05-15 21:32 UTC, Conaclos approved these changes
Thanks!

2024-05-15 21:34 UTC, Conaclos requested changes
Blocking while https://github.com/biomejs/website/pull/354 is not merged.

2024-05-16 10:58 UTC, Sec-ant commented
This can be merged now @Conaclos

2024-05-16 11:01 UTC, Conaclos approved these changes

2024-05-16 11:01 UTC, merged