feat(yaml): lexer that can lex very simple examples
biomejs/biome pull request #3430
Opened 2024-07-13 20:29 UTC by dyc3

## Summary

> [!WARNING]
> This PR is stacked on top of #3400. It requires rebasing once that one lands, before this can be merged. 

I figured I'd take a stab at building the lexer based on the grammar in #3400. It's somewhat inspired by the json lexer. I'm posting it early here so people can see it, and avoid duplicated effort.

related to: #3400

## Test Plan

Added some unit tests, and they all pass.

2024-07-14 07:07 UTC, ematipico requested changes
The JSON lexer is old and it hasn't been refactored yet.

In the meantime, we created a proper infrastructure for creating a lexer, and this is documented in the `CONTRIBUTING.md` file of the `biome_parser` crate. It is possible to reach this document from the main `CONTRIBUTING.md`, at the root of the repository.

The new infrastructure gives you many methods that you don't need to implement again, e.g. `peek_byte`, `consume_whitespace`

Also, avoid unchecked methods whenever possible.

2024-07-14 11:46 UTC, dyc3 commented on crates/biome_yaml_parser/src/lexer/mod.rs
> +    AfterInlineArray,
Ah, It would probably make more sense to use token flags for tracking what is possible to come next?

2024-07-14 11:47 UTC, dyc3 commented
> in the `CONTRIBUTING.md` file of the `biome_parser` crate.

Yeah that's the document I was referencing when writing this. That, and looking at the json lexer. Is there anything more than the "Implement a lexer" section of that doc? It's a little sparse on info.

2024-07-14 12:09 UTC, ematipico commented
Unfortunately that part still lacks some documentation due to some recent refactors. I completely forgot to follow up and add more to it

2024-07-16 13:02 UTC, ematipico commented
I suggest looking at the GraphQL parser and tokenizer. It's the most recent one

2024-08-27 09:40 UTC, Netail commented
@dyc3 any progress? 😅

2024-08-27 11:24 UTC, dyc3 commented
I haven't had time recently, but I could try and get this merged this week.

2024-08-27 14:08 UTC, ematipico approved these changes

2024-08-27 14:08 UTC, merged