feat(biome_js_analyzer): implement `useConsistentMemberAccessibility`
biomejs/biome pull request #3536
Opened 2024-07-28 17:22 UTC by seitarof

## Summary
close #3271 
implement [useConsistentMemberAccessibility](https://typescript-eslint.io/rules/explicit-member-accessibility/#require-explicit-accessibility-for-a-given-member)

## Test Plan
Add snaps for valid/invalid cases

2024-07-28 18:07 UTC, dyc3 requested changes

2024-07-28 18:07 UTC, dyc3 commented on crates/biome_js_analyze/src/lint/nursery/use_consistent_member_accessibility.rs
> +    fn is_no_public(&self) -> Option<bool> {
these functions could use some brief doc comments

2024-07-28 18:07 UTC, dyc3 commented on crates/biome_js_analyze/src/lint/nursery/use_consistent_member_accessibility.rs
> +    /// - `explicit` - requires an accessibility modifier for every member that allows that (a safe fix will add public).
It doesn't look like the fix is implemented for this yet.

2024-07-28 18:07 UTC, dyc3 commented on crates/biome_js_analyze/src/lint/nursery/use_consistent_member_accessibility.rs
> +        language: "js",
This should be `ts` right?
```suggestion
        language: "ts",
```

2024-08-07 14:19 UTC, chansuke commented on crates/biome_js_analyze/src/lint/nursery/use_consistent_member_accessibility.rs
> +    /// ### `accessibility`
Same as above. Let's put blank lines before and after a heading for compatibility

2024-08-07 14:19 UTC, chansuke commented on crates/biome_js_analyze/src/lint/nursery/use_consistent_member_accessibility.rs
> +        match ctx.options().accessibility {
could you make the variable(ex: let mut diag = RuleDiagnostic::new(// add common )) and make this code more DRY?
You can refer [here](https://github.com/biomejs/biome/blob/main/crates/biome_js_analyze/src/lint/style/use_const.rs#L112-L137) :)

2024-08-08 08:34 UTC, Conaclos reviewed
Thanks for your contribution! This looks already good! I left some comments and suggestions :)

2024-08-08 08:34 UTC, Conaclos commented on crates/biome_js_analyze/src/lint/nursery/use_consistent_member_accessibility.rs
> +    pub AnyMember = JsConstructorClassMember | JsPropertyClassMember | JsMethodClassMember | TsPropertyParameter | JsGetterClassMember | JsSetterClassMember
We should also cover:
- signature class members (i.e. member without body, i.e. abstract methods and properties)
- property parameters (for example `constructor(readonly prop) {}` where an accessibility is missing)

Also, I suggest renaming the node to `AnyJsMemberWithAccessibility`

```suggestion
    pub AnyJsMemberWithAccessibility = JsConstructorClassMember | JsPropertyClassMember | JsMethodClassMember | TsPropertyParameter | JsGetterClassMember | JsSetterClassMember
    | TsConstructorSignatureClassMember | TsMethodSignatureClassMember | TsPropertySignatureClassMember | TsGetterSignatureClassMember | TsSetterSignatureClassMember
	| TsPropertyParameter
```

To find the existing nodes, you can take a look at `xtask/codegen/js.ungramar`, we have `AnyJsClassMember`

2024-08-08 08:34 UTC, Conaclos commented on crates/biome_js_analyze/src/lint/nursery/use_consistent_member_accessibility.rs
> +impl AnyMember {
I think we could replace all these functions with a single one that returns the first encountered `TsAccessibilityModifier`. The function could thus return a `Option<TsAccessibilityModifier>`.

2024-08-09 07:49 UTC, seitarof commented on crates/biome_js_analyze/src/lint/nursery/use_consistent_member_accessibility.rs
> +    /// The following patterns are considered correct code with the default options `noPublic`:
Thanks for review!
fixed it 0ec7956

2024-08-16 13:15 UTC, chansuke commented on crates/biome_js_analyze/src/lint/nursery/use_consistent_member_accessibility.rs
> +    /// The following patterns are considered correct code with the default options `noPublic`:
:+1:

2024-08-29 17:09 UTC, Conaclos commented
@dyc3 @chansuke I updated the PR. I integrated the last reviews and I rebased on main (I squashed the commits to simplify the rebasing). Take a quick look and if everything is good we can merge :)

2024-08-29 17:09 UTC, Conaclos approved these changes

2024-08-29 19:25 UTC, chansuke commented on CHANGELOG.md
> +<<<<<<< HEAD
Should be removed

2024-08-29 19:27 UTC, chansuke commented on CHANGELOG.md
> +>>>>>>> 03501f3e17 (feat(biome_js_analyze): useConsistentMemberAccessibility)
same

2024-08-29 19:27 UTC, chansuke commented on CHANGELOG.md
> +<<<<<<< HEAD
same

2024-08-29 19:27 UTC, chansuke commented on CHANGELOG.md
> +>>>>>>> 03501f3e17 (feat(biome_js_analyze): useConsistentMemberAccessibility)
should be resolved

2024-08-29 19:31 UTC, chansuke commented
@Conaclos 
Thank you for your work:)
In `CHANGELOG` unresolved conflict is remaining

2024-08-30 09:25 UTC, merged

2024-09-02 14:02 UTC, seitarof commented
@Conaclos 
Thank you for your assistance!
I've been too busy with my main job and haven't been able to get started on this. I apologize for that 🙏