fix(analyze): Check if a fragment has only one child element using tokens.
biomejs/biome pull request #3582
Opened 2024-08-04 09:07 UTC by satojin219

## Summary

This bug occurs when a warning is supposed to be issued if a fragment has only one child element, but if line breaks or tabs are included, the warning does not appear. To check the number of child elements, child_list.len() is used, but this includes line breaks and tabs, causing the count of child elements to be more than one.
https://github.com/biomejs/biome/blob/main/crates/biome_js_analyze/src/lint/complexity/no_useless_fragments.rs#L165

 Therefore, I modified the code to scan the tokens of the fragment's children and check if there is only one `JsSyntaxKind::JSX_SELF_CLOSING_ELEMENT` or `JsSyntaxKind::JSX_ELEMENT`.

## Test Plan

Change the path on line 17 of `crates/biome_js_analyze/tests/quick_test.rs` to `tests/specs/complexity/noUselessFragments/issue_3545.jsx` and `tests/specs/complexity/noUselessFragments/withJsxElementInvalid.jsx.` Run the tests and confirm that both tests pass successfully.

closed #3545

2024-08-04 10:00 UTC, Conaclos commented
A test i s failing.
According to it the following code shoudl also be rreporetd as useless:

```jsx
<>
foo
</>
```

2024-08-04 15:17 UTC, ematipico requested changes

2024-08-04 15:17 UTC, ematipico commented on crates/biome_js_analyze/tests/specs/complexity/noUselessFragments/issue_3545.jsx.snap
> +    5 3 │
There's a regression here

2024-08-12 05:53 UTC, satojin219 commented
@Conaclos @ematipico 
I have fixed the bug, so please review again.

2024-08-13 12:35 UTC, ematipico commented
@satojin219  Can you update the changelog to describe your fix? https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md#writing-a-changelog-line

2024-08-13 14:17 UTC, satojin219 commented
@ematipico 
https://github.com/biomejs/biome/pull/3582#issuecomment-2286150152

[chore: updaste CHANGELOG.md](https://github.com/biomejs/biome/pull/3582/commits/fcd861c8f2271eab66e5ebad1bde086a08a3d1b5)
I've added it to the changelog!

2024-08-13 14:24 UTC, merged