refactor(noUnusedVariables): don't report unused function params
biomejs/biome pull request #3598
Opened 2024-08-06 11:18 UTC by Conaclos

## Summary

Fix #3596

## Test Plan

I updated the tests.

2024-08-06 11:20 UTC, dyc3 approved these changes

2024-08-06 12:36 UTC, ematipico requested changes
This is a breaking change, not a new feature. We can't merge this changes unless we intend to ship v2.0

The only thing we can do is to deprecate this rule for now.

2024-09-25 04:24 UTC, printfn commented
Why is this a breaking change given that changes to lint rules, including ones that add or remove errors, are common in minor version updates? Changes like this one should be fine in a minor update.

2024-09-25 14:02 UTC, ematipico commented
> Why is this a breaking change given that changes to lint rules, including ones that add or remove errors, are common in minor version updates? Changes like this one should be fine in a minor update.

Different reasons:
- we change the use case of the rule, which removes many use cases which users rely on;
- the rule `noUnusedVariables` is recommended, and it now suggests a rule that **isn't** recommended, this means that the user is forced to enable a new rule in order to achieve the same result;

2024-10-18 13:00 UTC, merged