fix(useHookAtTopLevel): avoid diagnostics on non react projects
biomejs/biome pull request #3826
Opened 2024-09-08 17:16 UTC by Javimtib92

## Summary

Closes #3476 

To avoid reporting diagnostics of this hook on non react projects I added a check to the `package.json` which should help on many of the edge cases. Like the methods from NestJS app starting with "use".

## Test Plan

I need a way to run the snapshots as if the tests were running with the 'react' dependency.  The CI tests should pass once this is done.

2024-09-08 18:10 UTC, Javimtib92 commented
@dyc3 Should I bump the version of the hook? And is there a way to simulate dependencies on the diagnostics ran by  declare_lint_rule?

https://github.com/biomejs/biome/blob/68dad5de3aaef650c158cd85631bae4385c76bd2/crates/biome_js_analyze/src/lint/correctness/use_hook_at_top_level.rs#L67

2024-09-08 21:43 UTC, dyc3 commented
No, the version field is the version of biome in which the rule became available, so leave that as is.

> is there a way to simulate dependencies

I have no idea, I've never had to do that before.

2024-09-09 08:18 UTC, Conaclos commented on crates/biome_js_analyze/src/lint/correctness/use_hook_at_top_level.rs
> +    })
I think we should return `true` by default if the manifest is not found. This ensures that the rule is usable even if we are not able to find the `package.json`.

```suggestion
    manifest.as_ref().map_or(true, |package_json| {
        package_json.dependencies.contains("react")
    })
```

2024-09-13 22:01 UTC, peaBerberian commented
Sorry if I missed something, but shouldn't we also at least look at the `devDependencies` key of the `package.json`?

I work on libraries where we sometimes use react for demo pages, development tools and/or tests. Those are generally not exposed to library users, and thus React is often only declared as a devDependency.
Yet they could profit from this rule.

I'm under the impression that:
> package_json.dependencies.contains("react")

Only applies to the `dependencies` key here, sorry if I'm mistaken.

2024-09-13 22:34 UTC, Conaclos commented
Please, note that I added [a comment in the issue](https://github.com/biomejs/biome/issues/3476#issuecomment-2337450550).

2024-09-14 09:43 UTC, Javimtib92 commented
> Sorry if I missed something, but shouldn't we also at least look at the `devDependencies` key of the `package.json`?
> 
> I work on libraries where we sometimes use react for demo pages, development tools and/or tests. Those are generally not exposed to library users, and thus React is often only declared as a devDependency. Yet we could profit from this rule.
> 
> I'm under the impression that:
> 
> > package_json.dependencies.contains("react")
> 
> Only applies to the `dependencies` key here, sorry if I'm mistaken.

I didn't think about that use case and I agree we should look at devDependencies too. Although I'm also waiting for an answer to the comment in the issue to understand better if what I tried to do here is really needed.

2024-09-14 10:28 UTC, peaBerberian commented
> Please, note that I added [a comment in the issue](https://github.com/biomejs/biome/issues/3476#issuecomment-2337450550).

Yes thanks,  I read the issue yet still added a comment in this PR just in case it turned out to be merged in the near future, as I'm only checking here sporadically.

I share the same linked interrogation, and I fear edge cases where that heuristic would produce false negatives.

> I didn't think about that use case and I agree we should look at devDependencies too

Thank you!

Just to go further through edge cases I'm wondering about: some project could theoretically have it only as an optional dependency or a peer dependency (like react-related libraries for example), or even not relying on a package manager and/or not having a `package.json` file at all in a JavaScript project.

E.g., I've worked with developers only relying on minified library bundles added as script tags in their HTML - and most browsers now also allows directly importing modules at runtime.
There's also people relying on alternate runtimes like `deno` which may not rely on a `package.json` file to manage dependencies.

Yet all of them could still be using biome and react, but maybe that's an unsupported usage?

2024-09-15 04:03 UTC, ematipico requested changes
Blocking for now, we haven't identified what's the real bug. Let's first discuss it in the relative issue.

2024-09-19 15:34 UTC, ematipico commented
I am going to close it for now, as it's up to the developer to enable this rule in this project.

We are going to provide a better system in the future, possibly for Biome v2.0, so users can enable framework-related rules via configuration.

2024-09-19 15:34 UTC, closed without merging