feat(biome_js_analyzer): implement noImplicitAnyLet
biomejs/biome pull request #395
Opened 2023-09-23 08:17 UTC by b4s36t4

Implements #389

## Summary

Creates a new rule to restrict the usage of variables without any type or initialisation in TS

More here -> https://www.typescriptlang.org/tsconfig#noImplicitAny

## Test Plan

Wrote test cases for valid and invalid situation, inspired form here #381

2023-09-23 08:24 UTC, b4s36t4 commented
Maybe `recommended` should be `false` for the rule? as the website is raising the lint errors 🤓.

2023-09-23 10:50 UTC, Conaclos reviewed
We should also add some tests in a JavaScript file to ensure that the rule does not affect JavaScript files.

2023-09-23 10:50 UTC, Conaclos commented on crates/biome_js_analyze/src/analyzers/nursery/no_implicit_any_let.rs
> +    ///
I could add more details:

```suggestion
    /// TypeScript variable declaration without any type annotation and initialization have the `any` type.
    /// The any type in TypeScript is a dangerous “escape hatch” from the type system.
    /// Using any disables many type checking rules and is generally best used only as a last resort or when prototyping code.
    /// TypeScript’s `--noImplicitAny` compiler option doesn't report this case.
```

2023-09-23 10:50 UTC, Conaclos commented on crates/biome_js_analyze/src/analyzers/nursery/no_implicit_any_let.rs
> +    /// Restrict use of implicit any type in Typescript.
```suggestion
    /// Disallow use of implicit `any` type on variable declarations.
```

2023-09-23 10:50 UTC, Conaclos commented on crates/biome_js_analyze/src/analyzers/nursery/no_implicit_any_let.rs
> +                    "Variable " <Emphasis>{variable.text()}</Emphasis> " has implicitly " <Emphasis>"any"</Emphasis> " type"
I think we can remove the variable name.

```suggestion
                    "This variable has implicitly the " <Emphasis>"any"</Emphasis> " type."
```

2023-09-23 10:50 UTC, Conaclos commented on crates/biome_js_analyze/src/analyzers/nursery/no_implicit_any_let.rs
> +                "Declare type or initialize the variable with some value"
We should also explain why the variable has implicitly the `any` type before suggesting a way to fix it.

```suggestion
                "Variable declarations without type annotation and initialization have implicitly the "<Emphasis>"any"</Emphasis>" type. Declare type or initialize the variable with some value."
```

2023-09-23 10:50 UTC, Conaclos commented on crates/biome_js_analyze/tests/specs/nursery/noImplicitAnyLet/invalid.ts
> +
Could you add some example with for loops, and multiple declarators?

e.g.

```ts
let x = 0, y, z = 0;
var x = 0, y, z = 0;
for(let a = 0, b; a < 5; a++) {}
```

2023-09-23 10:50 UTC, Conaclos commented on crates/biome_js_analyze/tests/specs/nursery/noImplicitAnyLet/valid.ts
> +
We should add `const`, [`using`](https://github.com/tc39/proposal-explicit-resource-management) and `for-of` examples to ensure that they are ignored.

e.g.

```ts
const x = 0;
for(let y of xs) {}
using z = f();
```

2023-09-23 10:52 UTC, Conaclos commented
> Maybe `recommended` should be `false` for the rule? as the website is raising the lint errors 🤓.

We can keep the rule as recommended. Thus, we have to fix the website. If it is too much work to do, then set `recommended` to `false` :)

2023-09-25 07:48 UTC, ematipico requested changes

2023-09-25 07:48 UTC, ematipico commented on crates/biome_js_analyze/src/analyzers/nursery/no_implicit_any_let.rs
> +    /// b = 1
Each snippet in the **invalid section** must raise only **one** diagnostic, this means that you'd need to break down this snippet in **four** code blocks with `expect_diagnostic` directive.

The valid section doesn't have this restriction.

2023-10-16 10:04 UTC, Conaclos commented
@b4s36t4 Are you still interested in completing this contribution?

2023-10-16 10:05 UTC, b4s36t4 commented
@Conaclos Yes, been sick past few days. Will complete this by End of this week.

2023-11-10 15:49 UTC, ematipico commented
Friendly ping @b4s36t4, are you still interested?

2023-11-13 04:01 UTC, TaKO8Ki commented
@Conaclos @ematipico Can I take over this pull request?

2023-11-13 08:14 UTC, ematipico commented
> @Conaclos @ematipico Can I take over this pull request? cc: @Conaclos

Sure, but please keep the commits of @b4s36t4 

You can see `git cherry-pick`

2023-11-13 14:09 UTC, TaKO8Ki commented
@ematipico Yes. I will also take over commits with "git cherry-pick".

2023-11-14 14:23 UTC, closed without merging