feat(markdown/parser): support thematic break block parser
biomejs/biome pull request #3982
Opened 2024-09-19 07:50 UTC by suxin2017

## Summary

support thematic break block parser
https://spec.commonmark.org/0.31.2/#thematic-breaks

## Test Plan

snap test

2024-09-19 13:14 UTC, dyc3 requested changes
I have a couple of implementation questions.

2024-09-19 13:14 UTC, dyc3 commented on crates/biome_markdown_parser/tests/md_test_suite/ok/thematic_break_block.md.snap
> +                    __token: UNDERSCORE@18..20 "_" [Newline("\n")] [],
The codegen here could use some improvement. This should be `underscore_token`.

2024-09-19 13:14 UTC, dyc3 commented on xtask/codegen/markdown.ungram
> +// Md Un-Grammar.
nit: keep the full name in this comment.
```suggestion
// Markdown Un-Grammar.
```

2024-09-19 13:14 UTC, dyc3 commented on xtask/codegen/markdown.ungram
> +MdIndent = value: 'Md_indent_chunk_literal'
nit: casing
```suggestion
MdHardLine = value: 'md_hard_line_literal'
MdSoftBreak = value: 'md_soft_break_literal'
MdTextual = value: 'md_textual_literal'
MdIndent = value: 'md_indent_chunk_literal'
```

2024-09-19 13:14 UTC, dyc3 commented on crates/biome_markdown_parser/src/syntax/thematic_break_block.rs
> +}
We have the `ParseNodeList` trait for parsing lists. See `impl ParseNodeList for ElementList` in the html parser for an example.

2024-09-19 13:39 UTC, ematipico requested changes

2024-09-19 13:39 UTC, ematipico commented on xtask/codegen/markdown.ungram
The rename of the nodes should be done in a separate PR, because it changes a lot of stuff and even though it's all codegen, it makes the review harder because we can't understand where are the new nodes.

2024-09-19 13:48 UTC, dyc3 commented on xtask/codegen/markdown.ungram
> +
Actually, thematic breaks can be _at least_ 3 chars (see example 50: https://spec.commonmark.org/0.31.2/#container-blocks-and-leaf-blocks)

2024-09-19 14:16 UTC, ematipico commented on xtask/codegen/markdown.ungram
> +
TIL so I suppose a list could make sense, then it's up to the parser to decide the nodes accordingly.

2024-09-23 03:45 UTC, suxin2017 commented
I think I have modified most of the problems. I wrote it again. Could you please help me see it again? thank you @ematipico @dyc3

2024-09-23 08:45 UTC, ematipico requested changes
There are few things to address, yet. Also, could you please address this comment? https://github.com/biomejs/biome/pull/3982/files#r1766848010

2024-09-23 08:45 UTC, ematipico commented on crates/biome_markdown_parser/src/lexer/tests.rs
> +    assert_lex! {
You should add a test case for newlines too, if you can

2024-09-23 08:45 UTC, ematipico commented on crates/biome_markdown_parser/src/lexer/mod.rs
> +        }
The lexer has already a function to consume whitespace, let's use that please: 

https://github.com/biomejs/biome/blob/47cb5d81f7f703b0ca149cda5e510dda6a0838f3/crates/biome_parser/src/lexer.rs#L84-L113

2024-09-23 08:45 UTC, ematipico commented on crates/biome_markdown_parser/src/syntax.rs
>  pub(crate) fn parse_any_block(p: &mut MarkdownParser) {
Parsing functions should always return a `ParsedSyntax`. Not returning a `ParsedSyntax` is considered a side effect, which we want to avoid

2024-09-23 08:45 UTC, ematipico commented on crates/biome_markdown_parser/src/syntax.rs
> +// use crate::syntax::thematic_break_block::{at_thematic_break_block, parse_thematic_break_block};
to remove

2024-09-23 08:45 UTC, ematipico commented on crates/biome_markdown_parser/src/token_source.rs
> +    pub fn before_whitespace_count(&self) -> usize {
Please document the function.

2024-09-23 08:45 UTC, ematipico commented on crates/biome_markdown_parser/src/token_source.rs
> +    }
To remove

2024-09-23 08:52 UTC, suxin2017 commented
> There are few things to address, yet. Also, could you please address this comment? https://github.com/biomejs/biome/pull/3982/files#r1766848010

Sorry for the rename change in this pr. This is because this is the first concrete implementation of the lexer to the parser, so the change is in this pr

2024-09-23 13:15 UTC, dyc3 approved these changes

2024-09-23 13:15 UTC, dyc3 commented on crates/biome_markdown_parser/src/lexer/mod.rs
> +    #[allow(dead_code)]
nit:
```suggestion
    #[expect(dead_code)]
```

2024-09-24 15:48 UTC, ematipico approved these changes

2024-09-24 15:48 UTC, ematipico commented on crates/biome_markdown_parser/src/token_source.rs
> +    /// tab will be counted as 4 spaces
Is there a link to the spec that says that? We need to justify certain decisions

2024-09-25 05:53 UTC, merged