feat(linter): implement noLowerCaseEnum
biomejs/biome pull request #4031
Opened 2024-09-21 17:47 UTC by eMerzh

## Summary

- it's globally accepted that enums should be in uppercase, although not a "spec requirement", some other tools have this lint.

please be indulgent, i'm a very noob in rust /o\ 

also there are no linked issue bc i'm not sure which one i should create.

## Test Plan

see tested

2024-09-21 20:43 UTC, eMerzh commented
mmh i have no idea for the ts enums 🤔  even if those are Graphql enums? 🤔  and if you want differents rules between gql & ts?

2024-09-21 20:49 UTC, dyc3 requested changes

2024-09-21 20:49 UTC, dyc3 commented on crates/biome_graphql_analyze/src/lint/nursery/no_lower_case_enum.rs
> +    type Query = Ast<GraphqlRoot>;
Your query should reference the actual node you are looking for, not the root node. So it should be `GraphqlEnumValueDefinition` and ...

2024-09-21 20:49 UTC, dyc3 commented on crates/biome_graphql_analyze/src/lint/nursery/no_lower_case_enum.rs
> +            .filter_map(GraphqlEnumValueDefinition::cast)
... That would let you avoid having to do this.

2024-09-21 20:52 UTC, dyc3 commented on crates/biome_graphql_analyze/src/lint/nursery/no_lower_case_enum.rs
> +    }
If this rule comes from an eslint plugin's rule, you should add it to `sources` here so that `biome migrate` can pick it up.

2024-09-21 21:41 UTC, dyc3 approved these changes

2024-09-21 21:43 UTC, dyc3 commented
I'll defer to somebody else for what the name for this rule should be. There should also be a changelog entry for this.

2024-09-21 21:50 UTC, eMerzh commented
thx for the quick review, I've added the changelog entry

2024-09-22 09:12 UTC, minht11 commented
I think originally the idea was that multiple languages can have the same rule. Like for example json language has `useSortedKeys`, the same rule could be implemented for javascript as well. `noLowerCaseEnum` could be part of `useNamingConvention` but for graphql, configuration would be separate for each language.  As far as I know currently there are no rules like that, so there are a lot of unanswered questions.

2024-11-30 17:01 UTC, ematipico commented
I renamed the rule to `useNamingConvention`

2024-11-30 17:02 UTC, merged