chore: refine README.kr.md
biomejs/biome pull request #4110
Opened 2024-09-27 17:45 UTC by StationSoen

## Summary
Refine Korean README Translation.

- Update some sections that differ from the README.md.
- Refine some slightly awkward sentences in the Korean README.md.
- Update the Japanese link to the default link.

## Tickets
- closes #3889

## Test Plan
- I’ll suggest a native Korean speaker as a reviewer, if that’s okay with you.

2024-10-01 21:32 UTC, Conaclos commented
> I’ll suggest a native Korean speaker as a reviewer, if that’s okay with you.

Yeah. Please :)

2024-10-14 06:13 UTC, quiple requested changes
원본 영어 문서에 맞춰서 업데이트 및 번역을 개선하고 맞춤법을 수정했습니다.

2024-10-14 06:13 UTC, quiple commented on packages/@biomejs/biome/README.kr.md
>  여러분이 코드를 작성할 때, 형식이 잘못된 코드에 format, lint 를 적용합니다.
```suggestion
```

2024-10-14 06:13 UTC, quiple commented on packages/@biomejs/biome/README.kr.md
>  ### 프로젝트 스폰서와 펀딩
```suggestion
### 프로젝트 스폰서십 및 펀딩
```

2024-10-14 06:13 UTC, quiple commented on packages/@biomejs/biome/README.kr.md
>  ## Biome 를 자세히 알아보기
```suggestion
## Biome에 대해 자세히 알아보기
```

2024-11-04 07:32 UTC, ematipico commented
@StationSoen can you apply the suggestions?

2024-11-04 07:44 UTC, StationSoen commented
@ematipico Sorry for the delay. I’ve applied all the feedback since it was very helpful.

2024-11-04 08:15 UTC, merged