feat(lint): add `no-head-element` from `eslint-plugin-next`
biomejs/biome pull request #4136
Opened 2024-09-30 09:44 UTC by kaioduarte

## Summary
Implement [no-head-element](https://nextjs.org/docs/messages/no-head-element) from `eslint-plugin-next`.

I'm willing to port the other rules if they're relevant to the project.

## Test Plan
Snapshots + CI

2024-09-30 10:09 UTC, ematipico requested changes
Some important changes to address:
- the name of the rule
- the documentation
- the diagnostic

2024-09-30 10:09 UTC, ematipico commented on crates/biome_js_analyze/src/lint/nursery/no_next_head_element.rs
> +            let is_in_app_dir = path.contains(&format!("app{}", std::path::MAIN_SEPARATOR));
The paths provided are always Unix-like paths, so there's no need to check against `MAIN_SEPARATOR`, which changes based on the OS. This means that the code won't work on Windows.

2024-09-30 10:09 UTC, ematipico commented on crates/biome_js_analyze/src/lint/nursery/no_next_head_element.rs
> +            let is_in_app_dir = path.contains(&format!("app{}", std::path::MAIN_SEPARATOR));
Line 67 allocates a string every time, which is not ideal. I suggest an alternative: use [`path.ancestors`](https://doc.rust-lang.org/std/path/struct.Path.html#method.ancestors), then called `rev()` to start from the end of the iterator, and the first `app` that is a folder you find will trigger the rule.

2024-09-30 10:09 UTC, ematipico commented on crates/biome_js_analyze/src/lint/nursery/no_next_head_element.rs
> +            },
Please refer to the contribution guide, the [three rule pillars](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md#explain-a-rule-to-the-user). This diagnostic doesn't explain why the use of `<head>` is an error.

2024-09-30 10:09 UTC, ematipico commented on crates/biome_test_utils/src/lib.rs
> +        panic!("Failed to find group and rule");
Can you provide a better message? This is mostly for us developers, so if this panics, we should provide a message that tells the developer how to fix the issue.

2024-09-30 10:09 UTC, ematipico commented on crates/biome_js_analyze/src/lint/nursery/no_next_head_element.rs
> +        language: "js",
```suggestion
        language: "jsx",
```

2024-09-30 10:09 UTC, ematipico commented on crates/biome_js_analyze/src/lint/nursery/no_next_head_element.rs
> +        name: "noNextHeadElement",
The rule should be called `noHeadElement`. The documentation will explain to the users that the rule is meant for a Next.js project

2024-09-30 10:15 UTC, kaioduarte commented on crates/biome_js_analyze/src/lint/nursery/no_next_head_element.rs
> +    /// // /pages/index.jsx
It actually runs everywhere except inside `/app` folder. I'll change that comment.

2024-10-01 10:07 UTC, ematipico approved these changes

2024-10-01 10:07 UTC, ematipico commented on crates/biome_js_analyze/src/lint/nursery/no_head_element.rs
> +            "Using "<Emphasis>"<head>"</Emphasis>" element can cause unexpected behavior in a Next.js application. Use "<Emphasis>"<Head />"</Emphasis>" from "<Emphasis>"next/head"</Emphasis>" instea
```suggestion
            "Using the "<Emphasis>"<head>"</Emphasis>" element can cause unexpected behavior in a Next.js application. Use "<Emphasis>"<Head />"</Emphasis>" from "<Emphasis>"next/head"</Emphasis>" instead."
```

2024-10-01 10:07 UTC, ematipico commented on crates/biome_js_analyze/src/lint/nursery/no_head_element.rs
> +    /// handled differently in Next.js.
```suggestion
    /// This rule only checks files that are outside of the [`app/` directory](https://nextjs.org/docs/app), as it's typically
    /// handled differently in Next.js.
```

2024-10-05 14:52 UTC, togami2864 approved these changes

2024-10-05 14:52 UTC, merged