feat(linter): noRestrictedImports add `patterns` option
biomejs/biome pull request #4302
Opened 2024-10-15 10:01 UTC by nekocode

## Summary

This PR add an option `patterns` similar to [no-restricted-imports#patterns](https://eslint.org/docs/latest/rules/no-restricted-imports#patterns) :

```json
"noRestrictedImports": {
    "options": {
        "paths": {
             "import-foo": "Using import-foo is not encouraged"
        },
        "patterns": {
             "import-foo/*": "Using import-foo is not encouraged"
        }
    }
}
```

## Test Plan

Changed snapshots

2024-10-15 13:45 UTC, Conaclos requested changes
Thank you for your contribution. I am holding this PR because we are in the process of merging it with `useImportRestrictions`. This needs some design work.

2024-12-12 14:01 UTC, boennemann commented
I just wanted to express that this rule would be highly beneficial for us. Is there a way to track progress on the merge with `useImportRestrictions`?

2025-03-13 00:12 UTC, rubencallewaert commented
Now that useImportRestriction has been removed in favor of no-restricted-imports. Are there plans to support this patterns feature? It's an extremely important capability for us and holding us back from considering biome.

2025-03-13 01:48 UTC, siketyan commented
@rubencallewaert see #5289.

2025-03-28 15:39 UTC, ematipico commented
Closing as it has been in stale for too long without updates. Follow https://github.com/biomejs/biome/issues/5289

2025-03-28 15:39 UTC, closed without merging