feat(graphql_analyze): noAnonymousOperations
biomejs/biome pull request #4337
Opened 2024-10-19 09:26 UTC by vohoanglong0107

## Summary

Disallow operations without name, since GraphQL clients usually use operations' name to cache.

## Test Plan

Added new tests to verify this rule's behavior

2024-10-19 14:37 UTC, ematipico requested changes

2024-10-19 14:37 UTC, ematipico commented on crates/biome_graphql_analyze/src/lint/nursery/no_anonymous_operations.rs
> +        let new_node = node.clone().detach().with_name(Some(new_name));
Do you need `detach` here?

2024-10-19 14:37 UTC, ematipico commented on crates/biome_graphql_analyze/src/lint/nursery/no_anonymous_operations.rs
> +                "Rename this "{state.operation_type}" to "{state.suggested_name}"."
Let's follow our rule pillars https://biomejs.dev/linter/#rule-pillars

This means that the .note must become a message that explains the error. The core action is the solution for fixing the error.

2024-10-19 14:37 UTC, ematipico commented on crates/biome_graphql_analyze/src/lint/nursery/no_anonymous_operations.rs
> +                suggested_name: get_suggested_name(node, operation_type),
We should allocate strings only when needed. Here, we should do it in the `action` function

2024-10-19 14:37 UTC, ematipico commented on crates/biome_graphql_analyze/src/lint/nursery/no_anonymous_operations.rs
> +        let operation_type = node.ty().ok()?.text();
Don't use `text` because it allocates a string, which isn't needed. Instead, use `syntax().text_trimmed()`

2024-10-19 14:37 UTC, ematipico commented on crates/biome_graphql_analyze/src/lint/nursery/no_anonymous_operations.rs
> +    let suggested_name = get_suggested_name_base_on_content(operation).unwrap_or(operation_type);
I don't see the need for two separate functions, because they are used once. Let's put everything in one single function

2024-10-23 05:48 UTC, ematipico commented on crates/biome_graphql_analyze/src/lint/nursery/no_anonymous_operations.rs
> +    /// Require specifying name for GraphQL operations.
```suggestion
    /// Enforce specifying the name of GraphQL operations.
```

2024-10-23 05:48 UTC, ematipico commented on crates/biome_graphql_analyze/src/lint/nursery/no_anonymous_operations.rs
> +    /// This is useful since most GraphQL client libraries are using the operation name for caching purposes.
```suggestion
    /// This is useful because most GraphQL client libraries use the operation name for caching purposes.
```

2024-10-23 05:48 UTC, ematipico commented on crates/biome_graphql_analyze/src/lint/nursery/no_anonymous_operations.rs
> +        name: "noAnonymousOperations",
I read the documentation, and it seems the rule is more focused on the name of the operations. It doesn't say anything about operations that don't have a name.

Wouldn't it make more sense to call the rule `useNamedOperation`? Plus, let's use the singular

2024-10-23 05:48 UTC, ematipico commented on crates/biome_graphql_analyze/src/lint/nursery/no_anonymous_operations.rs
> +                    "Anonymous GraphQL operations are forbidden. Make sure to name your " {operation_type.text()}"!"
```suggestion
                    "Anonymous GraphQL operations are forbidden. Make sure to name your " {operation_type.text()}"."
```

2024-10-23 05:48 UTC, ematipico commented on crates/biome_graphql_analyze/src/lint/nursery/no_anonymous_operations.rs
> +                "Most GraphQL client libraries use operation name for caching purposes."
```suggestion
                "Most GraphQL client libraries use the operation name for caching purposes."
```

2024-10-23 05:48 UTC, ematipico commented on crates/biome_graphql_analyze/src/lint/nursery/no_anonymous_operations.rs
> +                node.range(),
I think highlighting the whole query can be too much. You used very small examples, but if you enable the rule in a big project, the whole thing is going to be red, which isn't ideal for the users. What do you think if we highlight the operation instead?

2024-10-27 10:57 UTC, ematipico approved these changes

2024-10-27 11:13 UTC, vohoanglong0107 commented
Oops, my bad, didn't mean to re-request a review from you there 😅

2024-10-27 11:54 UTC, merged