fix(biome_css_parser): fixed css @document parser error
biomejs/biome pull request #4350
Opened 2024-10-21 04:23 UTC by eryue0220

## Summary

Closed: https://github.com/biomejs/biome/issues/4258
## Test Plan

Add test cases:
```css
@-moz-document url-prefix() {}
@-moz-document url-prefix("https://www.example.com/") {}
@-moz-document url-prefix() {
	body {
		background-color: green;
	}
}
@-moz-document url-prefix("https://www.example.com/") {
	body {
		background-color: green;
	}
}
```

2024-10-21 04:31 UTC, eryue0220 commented
@chansuke I have no idea about the ci error, it seemed that the git check didn't check any change in my pr?

2024-10-21 05:14 UTC, ematipico requested changes

2024-10-21 05:14 UTC, ematipico commented on crates/biome_css_syntax/src/generated/nodes.rs
@eryue0220 you need to remove this file from your PR.

It's possible that your main branch is out of date, so it generates an outdated file.

2024-10-23 04:27 UTC, eryue0220 commented on crates/biome_css_syntax/src/generated/nodes.rs
Thanks, fixed it.

2024-10-23 05:20 UTC, ematipico approved these changes

2024-10-23 05:20 UTC, merged