feat(linter): add `noGlobalDirnameFilename`
biomejs/biome pull request #4452
Opened 2024-11-02 15:52 UTC by unvalley

## Summary

## Test Plan

2024-11-06 06:28 UTC, ematipico requested changes

2024-11-06 06:28 UTC, ematipico commented on crates/biome_js_analyze/src/lint/nursery/no_global_dirname_filename.rs
> +        let mut signals = vec![];
You don't need a vector of signals. Only one is enough in this rule

```rs
    type Signals = Option<Self::State>;
```

2024-11-06 06:28 UTC, ematipico commented on crates/biome_js_analyze/src/lint/nursery/no_global_dirname_filename.rs
> +        let model = ctx.model();
This rule should check if we're evaluating a script file `.cjs`, and if so, the rule should bail because they are valid in a CommonJS file

2024-11-06 17:31 UTC, unvalley commented
Thank you, I've addressed review.

2024-11-07 12:48 UTC, ematipico commented
I'm not really sure I understand the rule.

I thought the rule was to trigger `__filename` inside ESM files and propose a code action. But it seems the rule does trigger in CJS files, where `import.meta` isn't valid

2024-11-07 13:33 UTC, unvalley commented
@ematipico 
I was confused and mistaken that I should trigger when migrating from `cjs` to `esm`. I've checked the original rule and you are correct.

https://github.com/sindresorhus/eslint-plugin-unicorn/blob/0d91fe8530611f68a95261e2a8f5f80b12caee35/rules/prefer-module.js#L253

Thank you, I have fixed it.

2024-11-12 08:05 UTC, ematipico approved these changes

2024-11-12 08:05 UTC, merged