fix(js_formatter): updated the is_test_call_expression function to match prettier
biomejs/biome pull request #4811
Opened 2024-12-30 10:20 UTC by mdm317

## Summary

> https://github.com/prettier/prettier/blob/d9d0999aac70c04b06b35cbcb2c804b4a9c8d8a8/src/language-js/utils/index.js#L383-L387

For Prettier, assume it is a Testcall only if the first argument is a StringLiteral or TemplateLiteral.
So, I added the logic.
However, assuming that it is not a Testcall if the first argument is neither a StringLiteral nor a TemplateLiteral might have some edge cases. 
Please share your thoughts.

## Test Plan

add test

2025-01-02 16:26 UTC, mdm317 commented
in ci
> error: test failed, to rerun pass `-p biome_js_formatter --test prettier_tests` 

I don't understand why this error occurs, even though the issue-4202.js.prettier-snap file exists.
Can someone help me?

2025-01-02 16:31 UTC, dyc3 requested changes

2025-01-02 16:31 UTC, dyc3 commented on crates/biome_js_formatter/tests/specs/prettier/js/test-declarations/Issue-4202.js
The tests in `specs/prettier` are synced with the prettier repo. You should move your new snapshot tests outside of that folder into `specs`.

2025-01-03 09:33 UTC, ematipico commented on crates/biome_js_formatter/tests/specs/prettier/js/test-declarations/Issue-4202.js
@mdm317 Also, you should add template literals to the tests, since they are part of the new logic

2025-01-05 14:35 UTC, mdm317 commented on crates/biome_js_formatter/tests/specs/prettier/js/test-declarations/Issue-4202.js
@dyc3 
Thank you for letting me know. It was really helpful!

@ematipico 
Thank you for the review. I have one question.
> https://github.com/biomejs/biome/blob/a658a294087c143b83350cbeb6b44f7a2e9afdd1/crates/biome_js_formatter/tests/specs/prettier/js/test-declarations/test_declarations.js.prettier-snap#L19-L21

Template literals are already exist, and the results won't change.
Should I still add them? 
If I misunderstood something, please let me know.

2025-01-05 15:33 UTC, dyc3 approved these changes

2025-01-07 07:03 UTC, ematipico commented
@mdm317 can you please add another test case with template literals?

2025-01-09 15:17 UTC, ematipico approved these changes

2025-01-09 15:17 UTC, merged