feat(lint): new `useValidAriaRole `
biomejs/biome pull request #553
Opened 2023-10-19 17:50 UTC by vasucp1207

## Summary

Closes https://github.com/biomejs/biome/issues/526

## Test Plan

2023-10-20 07:41 UTC, ematipico requested changes
Thank you! I am going to block for now while we focus only on bug fixes :)

2023-10-22 07:45 UTC, nissy-dev requested changes
Thank you for your contributions! I added some comments.

2023-10-22 07:45 UTC, nissy-dev commented on crates/biome_js_analyze/src/aria_analyzers/nursery/use_valid_aria_role.rs
> +        }
I think these lines are not necessary. This is because `aria_roles.get_role` return None if role is null or undefined.

2023-10-22 07:45 UTC, nissy-dev commented on crates/biome_js_analyze/src/aria_analyzers/nursery/use_valid_aria_role.rs
> +        }
I think these lines are not necessary. This is because `aria_roles.get_role` return None if role is null or undefined.

2023-10-22 07:45 UTC, nissy-dev commented on crates/biome_js_analyze/tests/specs/nursery/useValidAriaRole/invalid.jsx
> +<>
You should add eslint's tests as much as possible
ref: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/__tests__/src/rules/aria-role-test.js

2023-10-22 07:45 UTC, nissy-dev commented on crates/biome_js_analyze/tests/specs/nursery/useValidAriaRole/valid.jsx
> +<>
You should add eslint's tests as much as possible
ref: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/__tests__/src/rules/aria-role-test.js

2023-10-22 07:45 UTC, nissy-dev commented on crates/biome_js_analyze/src/aria_analyzers/nursery/use_valid_aria_role.rs
> +}
It is good that you implemented the option :+1:

2023-10-22 07:45 UTC, nissy-dev commented on crates/biome_js_analyze/src/aria_analyzers/nursery/use_valid_aria_role.rs
> +        }
I think these lines are not necessary. We need to check the role for the custom component as well.

2023-10-22 07:45 UTC, nissy-dev commented on crates/biome_js_analyze/src/aria_analyzers/nursery/use_valid_aria_role.rs
> +            })
These lines are not necessary because it seem to be a duplicate of the above.

2023-10-22 18:52 UTC, vasucp1207 commented
Now it also checks for attr val like `"row range"` by splitting the string. Also I think some roles are missing [roles.rs](https://github.com/biomejs/biome/blob/5179abd24b315194416f357afe6b69e11e6470e7/crates/biome_aria/src/roles.rs#L825) like `tabpanel`, `treegrid` etc, there are 78 in total in [wai-aria](https://www.w3.org/TR/wai-aria/#namefromauthor)?

2023-10-23 10:27 UTC, ematipico requested changes

2023-10-23 10:27 UTC, ematipico commented on crates/biome_js_analyze/src/aria_analyzers/nursery/use_valid_aria_role.rs
> +    /// Elements with ARIA roles must use a valid, non-abstract ARIA role.
```suggestion
    /// Elements with ARIA roles must use valid, non-abstract ARIA attributes.
```

2023-10-23 10:27 UTC, ematipico commented on crates/biome_js_analyze/src/aria_analyzers/nursery/use_valid_aria_role.rs
> +                    "Enforce that elements with ARIA roles must use a valid, non-abstract ARIA role."
This is the phrase you want in the documentation, not here. Here, you want to have something like "The role **<ROLE_NAME>** doesn't exist", or `"The role **<ROLE_NAME> is abstract and can't be applied.*

2023-10-23 10:27 UTC, ematipico commented on crates/biome_js_analyze/src/aria_analyzers/nursery/use_valid_aria_role.rs
> +                "Check "<Hyperlink href="https://www.w3.org/TR/wai-aria/#namefromauthor">"wai-aria"</Hyperlink>" for valid roles or provide options accordingly."
```suggestion
                "Check "<Hyperlink href="https://www.w3.org/TR/wai-aria/#namefromauthor">"WAI-ARIA"</Hyperlink>" for valid roles or provide options accordingly."
```

2023-10-23 10:27 UTC, ematipico commented on crates/biome_js_analyze/src/aria_analyzers/nursery/use_valid_aria_role.rs
> +        recommended: false,
This should be recommended, I think. ARIA rules are very important.

2023-10-23 10:27 UTC, ematipico commented on crates/biome_js_analyze/src/aria_analyzers/nursery/use_valid_aria_role.rs
> +}
You created an option, but it seems we are not using it. In order to "wire" an option to Biome, you have to:
1. Add it to the list of rules that have options:
https://github.com/biomejs/biome/blob/e6c12c0fed2a1b1662f2f228d369917dd58b7a5c/crates/biome_js_analyze/src/options.rs#L30-L42

https://github.com/biomejs/biome/blob/e6c12c0fed2a1b1662f2f228d369917dd58b7a5c/crates/biome_js_analyze/src/options.rs#L54

https://github.com/biomejs/biome/blob/e6c12c0fed2a1b1662f2f228d369917dd58b7a5c/crates/biome_js_analyze/src/options.rs#L155

2. You must apply all the correct macros, here's an example:
https://github.com/biomejs/biome/blob/e6c12c0fed2a1b1662f2f228d369917dd58b7a5c/crates/biome_js_analyze/src/semantic_analyzers/style/no_restricted_globals.rs#L62-L70

3. Apply `FromStr`, with no fancy implementation
https://github.com/biomejs/biome/blob/e6c12c0fed2a1b1662f2f228d369917dd58b7a5c/crates/biome_js_analyze/src/semantic_analyzers/style/no_restricted_globals.rs#L77

4. And apply our internal deserialisation
https://github.com/biomejs/biome/blob/e6c12c0fed2a1b1662f2f228d369917dd58b7a5c/crates/biome_js_analyze/src/semantic_analyzers/style/no_restricted_globals.rs#L86-L109


For testing, the guide should help you: https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md#rule-configuration


Once you've done this, there are two missing things:
- add documentation comments for `allowed_invalid_roles` and `ignore_non_dom` and explain what they do
- update the documentation of this rule by adding the options and explaining them:
https://github.com/biomejs/biome/blob/e6c12c0fed2a1b1662f2f228d369917dd58b7a5c/crates/biome_js_analyze/src/semantic_analyzers/style/no_restricted_globals.rs#L35-L50

2023-10-30 03:20 UTC, nissy-dev commented
> Now it also checks for attr val like "row range" by splitting the string. Also I think some roles are missing [roles.rs](https://github.com/biomejs/biome/blob/5179abd24b315194416f357afe6b69e11e6470e7/crates/biome_aria/src/roles.rs#L825) like tabpanel, treegrid etc, there are 78 in total in [wai-aria](https://www.w3.org/TR/wai-aria/#namefromauthor)?

I have created the PR (#629) about this.

2023-10-30 09:26 UTC, Conaclos commented on crates/biome_js_analyze/src/aria_analyzers/nursery/use_valid_aria_role.rs
> +    }
Don't forget to rebase your work on main. I pushed some changes related to config parsing. In the process I removed `visit_member_name`. I introduced `report_unknown_map_key` that you can use directly in `visit_map`.

2023-11-08 18:35 UTC, ematipico approved these changes
I think we can merge, we should resolve the conflicts

2023-11-13 13:37 UTC, Conaclos approved these changes
Thanks!

2023-11-13 13:37 UTC, merged