feat(lint/noDefaultExport): add rule
biomejs/biome pull request #599
Opened 2023-10-25 13:26 UTC by Conaclos

## Summary

Implement [no-default-export](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-default-export.md).

This is a rule often recommended in code style. For example the Google's TypeScript code style [discourages the use of default exports](https://google.github.io/styleguide/tsguide.html#exports).

## Test Plan

Unit tests and doc tests should pass.

2023-10-25 16:19 UTC, victor-teles commented
@Conaclos Looks good to me!

I'd like to suggest add two more test cases:

Re-export the default from other module:
```javascript 
export { default } from './module';
```

export default using `as`
```javascript 
export { member as default };
```

2023-10-26 08:44 UTC, ematipico reviewed
I believe this rule requires more work. Also, an important question: you mentioned CommonJS in the documentation, but it seems that `module.exports` is not covered by this rule. Is it intentional? If so, we have to explain it in the documentation. If not, we should take that into account in the implementation of the rule.

2023-10-26 08:44 UTC, ematipico commented on crates/biome_js_analyze/src/analyzers/nursery/no_default_export.rs
> +    /// Disallow `export default`.
The rule is about "default exports" in general, NOT about `export default`. If we document it like this, users might think that grammar like `export { module as default }` is legal but it shouldn't

2023-10-26 08:44 UTC, ematipico commented on crates/biome_js_analyze/src/analyzers/nursery/no_default_export.rs
> +    /// Also, named exports improve consistency by using the same name through a code base.
The rule is about default exports, so the documentation should explain why this rule bans them. We should not mention them. So we should highlight **why the rule bans them**. The rule is called "noDefaultExports, no `useNamedExports` :)

2023-10-26 08:44 UTC, ematipico commented on crates/biome_js_analyze/src/analyzers/nursery/no_default_export.rs
> +                    "Use a named export instead."
Based on [our pillars](https://biomejs.dev/linter/#rule-pillars), we should fix and explain the error, so this message should tell that a default export was detected and it's an error.

Then, we should explain why it's an error, maybe by telling the users about discoverability. Then, at the end, we can suggest using a named export.

2023-10-26 08:44 UTC, ematipico commented on crates/biome_js_analyze/tests/specs/nursery/noDefaultExport/invalid.json.snap
> +  > 1 │ export default function f() {};
The range should highlight `export default` or `default`. It should not point to the whole function.

2023-10-30 12:06 UTC, ematipico requested changes
The rule doesn't say that default exports in node - `module.exports` -  are **supported**. We should add at least one example.

2023-10-30 23:24 UTC, ematipico commented
Well I don't know, the rule still doesn't say anything about it. You need to tell us 😅

2023-11-13 13:45 UTC, merged