fix/added-guide-to-explain-how-biome-behaves-with-new-files
biomejs/biome pull request #624
Opened 2023-10-29 16:46 UTC by TheShiveshNetwork

## Summary

Fix #587 
This PR adds the file `BIOME_BEHAVIOURS.md` for the guide to explain how biome behaves with new files.

## Test Plan

2023-10-30 11:01 UTC, ematipico requested changes
Here's some early feedback:

- we want to copy all this content
	https://github.com/biomejs/biome/blob/4464e561296d1e753b4873697d1818fe1a5f2605/website/src/content/docs/reference/configuration.mdx#L11-L65
- we need to remove the content from `configuration.mdx`
	
- the page should be called `biome-behaviour.mdx`
- the page doesn't have the correct frontmatter, like this one:
	https://github.com/biomejs/biome/blob/4464e561296d1e753b4873697d1818fe1a5f2605/website/src/content/docs/guides/getting-started.mdx#L1-L4
- the page needs to be added to the sidebar
	https://github.com/biomejs/biome/blob/4464e561296d1e753b4873697d1818fe1a5f2605/website/astro.config.ts#L171-L181

2023-10-30 11:03 UTC, ematipico commented
@TheShiveshNetwork please make sure to [website locally](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md#website-development), because with the current changes, the page **doesn't** appear in the website.

2023-10-30 12:03 UTC, TheShiveshNetwork commented
@ematipico alright! Working on it.

2023-10-30 16:39 UTC, TheShiveshNetwork commented
@ematipico Just pushed a commit, tell me if I missed something. I am ready for further improvisations.

2023-10-30 16:42 UTC, TheShiveshNetwork commented
And yeah, can you help me with the project setup and how do I run this project locally, because when I use the command
`just install-tools`
I get
`error: Recipe 'install-tools' could not be run because just could not find the shell: program not found`.

2023-10-31 16:02 UTC, ematipico commented
That's weird, I have never seen that error. Did you install rust on your machine?

2023-11-01 12:47 UTC, TheShiveshNetwork commented
@ematipico Sorry to disturb you again. But can you check this now?
I removed the dependancy
`"@biomejs/wasm-web": "link:../packages/@biomejs/wasm-web",`
And commented the places where it was used.

2023-11-01 13:56 UTC, ematipico commented
Hey @TheShiveshNetwork , I think there was a misunderstanding.

You should **not** remove the things I asked you to comment, I suggested you to that **locally** on your machine so you could start the dev server of the website on your machine.

2023-11-01 13:59 UTC, ematipico commented on biome-behaviour.mdx
> +---
This isn't correct, it should not be copied. I just showed you **an example**, but here you have:

```
---
title: How Biome works
description: Understand how the Biome toolchain works
---
```

2023-11-01 17:37 UTC, TheShiveshNetwork commented
Sorry from my end, I misunderstood it! I'll make another commit.

2023-11-02 07:26 UTC, ematipico commented
Thank you @TheShiveshNetwork , I will take it from here

2023-11-02 07:27 UTC, merged

2023-11-02 15:38 UTC, TheShiveshNetwork commented
Thanks @ematipico it was a great experience working on this, with your suggestions and help.