doc(ja): translate `credits` into Japanese
biomejs/biome pull request #903
Opened 2023-11-27 08:15 UTC by hitohata

## Summary

I've translated the credits page. 

Related to: #880 

## Test Plan

2023-11-27 10:07 UTC, nissy-dev commented
I'll review

2023-11-27 10:22 UTC, nissy-dev requested changes
翻訳ありがとうございます！コメントしたところは commit suggestion ボタンで修正してもらえると助かります 🙏

2023-11-27 10:22 UTC, nissy-dev commented on website/src/content/docs/ja/internals/credits.mdx
> +description: これまでのコントリビューターと私達に影響を与えたプロジェクトへの謝辞
```suggestion
description: これまでのコントリビューターと Biome に影響を与えたプロジェクトへの謝辞
```

2023-11-27 10:22 UTC, nissy-dev commented on website/src/content/docs/ja/internals/credits.mdx
> +## フォーク
```suggestion
## フォークしたプロジェクト
```

2023-11-27 10:22 UTC, nissy-dev commented on website/src/content/docs/ja/internals/credits.mdx
> +Biomeは[Rome Tools](https://github.com/biomejs/biome/)のコミュニティフォークです。
```suggestion
Biomeは、[Rome Tools](https://github.com/biomejs/biome/)のコミュニティによるフォークです。
```

2023-11-27 10:22 UTC, nissy-dev commented on website/src/content/docs/ja/internals/credits.mdx
> +_Rome Tools_ と _Biome_ はMITライセンスに基づいています。
```suggestion
_Rome Tools_ と _Biome_ は、MITライセンスに基づいています。
```

2023-11-27 10:22 UTC, nissy-dev commented on website/src/content/docs/ja/internals/credits.mdx
> +それらのコードは何らかの方法にて変換され、ときには大幅に書き直されています。
```suggestion
それらのコードは、自分たちのコードに合うように変換されたり、ときには大幅に書き直されたりしています。
```

2023-11-27 10:22 UTC, nissy-dev commented on website/src/content/docs/ja/internals/credits.mdx
> +Biomeには他のプロジェクトからフォークしたコードが含まれています。
```suggestion
Biomeには、他のプロジェクトからフォークしたコードが含まれています。
```

2023-11-27 10:22 UTC, nissy-dev commented on website/src/content/docs/ja/internals/credits.mdx
> +Biomeには他のプロジェクトから多大な影響を受けたコードが含まれています。それらはBiomeの言語/インフラストラクチャに適応されています。
```suggestion
Biomeには、他のプロジェクトから大きな影響を受けたコードが含まれています。それらは、Biomeのインフラストラクチャに適応されています。
```

2023-11-28 04:23 UTC, nissy-dev approved these changes
Thank you for your contribution!

2023-11-28 04:29 UTC, merged

2023-11-28 08:53 UTC, hitohata commented
Sorry for the late reply and action...
Thank you for merging!