doc(ja): translate `Formatter` doc into Japanese
biomejs/biome pull request #904
Opened 2023-11-27 09:03 UTC by Gumichocopengin8

## Summary
Partial work of #880. ` formatter/index.mdx`

## Test Plan
- Check if all links works as expecetd
- Check if all translations make sense

2023-11-27 10:30 UTC, nissy-dev commented
I'm working for review

2023-11-27 12:19 UTC, nissy-dev requested changes
翻訳ありがとうございます！コメントしたところは確認してもらって、問題なければcommit suggestion ボタンで修正してもらえると助かります 🙏

2023-11-27 12:19 UTC, nissy-dev commented on website/src/content/docs/ja/formatter/index.mdx
> +そのような場合はフォーマット抑制コメントが使用できます。
```suggestion
そのような場合はフォーマットを抑制するコメントが使用できます。
```

2023-11-27 12:19 UTC, nissy-dev commented on website/src/content/docs/ja/formatter/index.mdx
> +デフォルトではフォーマッターはコードを**チェック**し、フォーマットに変更がある場合に診断情報を生成します。
```suggestion
デフォルトでは、フォーマッターはコードを**チェック**し、差分がある場合はそれを報告します。
```

2023-11-27 12:19 UTC, nissy-dev commented on website/src/content/docs/ja/formatter/index.mdx
> +本当に重要なことに集中できるようにしています。
```suggestion
チーム内での[本質的でない議論](https://ja.wikipedia.org/wiki/パーキンソンの凡俗法則)を防ぎ、本当に重要なことに集中できるようにするために、
[新しいオプションを意図的に追加しない](https://github.com/prettier/prettier/issues/40)ようにしています。
```

2023-11-27 12:47 UTC, unvalley commented on website/src/content/docs/ja/formatter/index.mdx
> +Biomeはスタイル関する論争に終止符を打つことを目的とした、絶対的なフォーマッターです。
How about unifying "formatter" instead of "フォーマッター"?, lint as well.

2023-11-28 03:01 UTC, Gumichocopengin8 commented
修正しました。

2023-11-28 03:30 UTC, unvalley approved these changes
Thank you!

2023-11-28 04:19 UTC, nissy-dev approved these changes

2023-11-28 04:19 UTC, merged