doc(ja): translate `Architecture` into Japanese
biomejs/biome pull request #912
Opened 2023-11-27 18:22 UTC by seo1nk

## Summary

Partial work of https://github.com/biomejs/biome/issues/880 .
I've translated `internals/architecture.mdx`.

## Test Plan

2023-11-28 04:47 UTC, TaKO8Ki requested changes
Thank you for the contribution. I left some suggestions.

2023-11-28 04:47 UTC, TaKO8Ki commented on website/src/content/docs/ja/internals/architecture.mdx
> +このドキュメントでは Biome の内部機能の一部と、それらがプロジェクト内でどのように利用されているかについて説明します。
```suggestion
このドキュメントでは、 Biome の内部機能の一部と、それらがプロジェクト内でどのように利用されているかについて説明します。
```

2023-11-28 04:47 UTC, TaKO8Ki commented on website/src/content/docs/ja/internals/architecture.mdx
> +以下の例では `while` の括弧が抜けていますが、パーサーは上手く回復し、適切な CST でコードを表現できています。
```suggestion
以下の例では、 `while` の括弧が抜けていますが、パーサーは上手く回復し、適切な CST でコードを表現できています。
```

2023-11-28 04:47 UTC, TaKO8Ki commented on website/src/content/docs/ja/internals/architecture.mdx
> +このノードは、構文エラーに起因する破損コードを装飾するのに利用されます。
```suggestion
パーサーは誤った構文を処理することからコンシューマーを保護するため、 `Bogus` ノードも使用します。
このノードは、構文エラーに起因する破損したコードを装飾するのに利用されます。
```

2023-11-28 12:41 UTC, seo1nk commented
@TaKO8Ki 
Thank you, fix completed!

2023-11-29 01:46 UTC, TaKO8Ki requested changes
I left one more suggestion. After addressing it, LGTM :)

2023-11-29 01:46 UTC, TaKO8Ki commented on website/src/content/docs/ja/internals/architecture.mdx
> +title: Architecture
```suggestion
title: アーキテクチャ
```

2023-11-29 12:45 UTC, nissy-dev approved these changes
Thanks!

2023-11-29 13:20 UTC, TaKO8Ki approved these changes
Thanks!

2023-11-29 13:20 UTC, merged