wip
biomejs/biome pull request #963
Opened 2023-11-29 16:19 UTC by Conaclos

## Summary

Implement `useFilenamingCOnvention` rule that enforces the use of conventional filenames for JavaScript and TypeScript.

The rule provides 4 possibel cases (all enabled by default):
- camelCase
- kebab-case
- snake_case
- export: a special case that allows reusing teh name of an export as the filename

SImilarly to `useNamingConvention`, we provide a `strictCase` option (enbaled by default) that forbids consecutive uppercase letter for camelCase.

The `filenameCases` option takes an array of allowed cases.

## Test Plan

Tests added.

2023-11-30 16:00 UTC, unvalley commented on crates/biome_js_analyze/tests/specs/nursery/useFilenamingConvention/validSTrictCase.js
nits filename typo: validStrictCase.js.snap

2023-11-30 16:00 UTC, unvalley commented on crates/biome_js_analyze/tests/specs/nursery/useFilenamingConvention/invalidSTrictCase.js
nits filename typo: `invalidStrictCase.js`

2023-11-30 16:01 UTC, unvalley commented on crates/biome_js_analyze/src/analyzers/nursery/use_filenaming_convention.rs
> +    /// Enforce naming conventions for JavaScript and typeScript filenames.
```suggestion
    /// Enforce naming conventions for JavaScript and TypeScript filenames.
```

2023-11-30 16:20 UTC, unvalley commented
The implementation looks good to me. I like this rule!

2023-12-02 20:03 UTC, ematipico commented
Have you considered using `SemanticServices` and add a function that returns the exported binding? (In case we don't have it)

2023-12-04 12:07 UTC, ematipico requested changes
Blocking until we solve the stack overflow issue. That's concerning.

2023-12-21 19:05 UTC, Conaclos commented
> Blocking until we solve the stack overflow issue. That's concerning.

Basing this PR on #1283, solve the issue :)

2023-12-22 12:48 UTC, merged