feat(website): Introduction to textlint
biomejs/biome pull request #986
Opened 2023-12-01 02:27 UTC by yossydev

This PR is not yet complete.
Once I have added the rules, I will eliminate the errors that appear in `pnpm textlint` after I get your review to see if I can implement these rules!

## Summary

- Related comments: https://github.com/biomejs/biome/issues/880#issuecomment-1831826077

### Other OSS translation projects and the textlint rules used in them

-  [Next.js](https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs)
    - textlint-rule-preset-ja-technical-writing
    - textlint-rule-max-comma
    - textlint-rule-preset-ja-spacing
-  [sveltekit](https://github.com/svelte-jp/kit) & [svelte-site-jp](https://github.com/svelte-jp/svelte-site-jp)
    - textlint-rule-detect-bad-chars
    - textlint-rule-no-mix-dearu-desumasu
    - textlint-rule-preset-jtf-style
- [React](https://github.com/reactjs/ja.react.dev)
  - textlint-rule-preset-jtf-style
- [Vue](https://github.com/vuejs/jp.vuejs.org)
  - textlint-rule-detect-bad-chars
  - textlint-rule-no-mix-dearu-desumasu
  - textlint-rule-preset-jtf-style
-  [Vite](https://github.com/vitejs/docs-ja)
    - textlint-rule-preset-jtf-style

I have installed `textlint-rule-preset-jtf-style` which is the most used of them all!

## Test Plan

- CI is successful.
- No problem with the rules you set.

2023-12-01 02:29 UTC, yossydev commented on website/.textlintrc.json
> +			"4.3.7.山かっこ<>": false
This is taken from react's textlint rule

https://github.com/reactjs/ja.react.dev/blob/30d3e7c9a6169f130b11420d9466c18be5eba5b5/textlint/.textlintrc.json#L6-L13

2023-12-01 02:30 UTC, yossydev commented on .github/workflows/website_deploy_preview.yml
> +        run: pnpm textlint
What about having `website_deploy_preview` run textlint??:eyes:

2023-12-02 04:12 UTC, nissy-dev requested changes
Thank you for your investigation! I left some comments, please check it.

@unvalley I don't have personal opinions about settings. If you have , please give some advice about settings like prh.yaml etc.

2023-12-02 11:33 UTC, unvalley commented on website/prh.yml
> +    patterns: リント
We should add more patterns, but 
```suggestion
  - expected: lint
    patterns: リント
  - expected: linter
    patterns: 
      - リンター
      - リンタ  
  - expected: formatter
    patterns:
      - フォーマッター
      - フォーマッタ
```

2023-12-04 14:09 UTC, yossydev reviewed
Now that the rules have been decided, pn textlint:fix has been used to resolve the syntax errors that were currently there:pray:.

[fix: formatting by textlint:fix](https://github.com/biomejs/biome/pull/986/commits/58caa8ed346e5d9973f0e7ffd4f2f483cf1fcd16)

2023-12-04 14:15 UTC, unvalley commented on .github/workflows/website_deploy_preview.yml
> +        run: pnpm textlint
This file diff can be removed?

2023-12-04 14:23 UTC, yossydev commented on website/prh.yml
> +      - リンタ
It's outrageous!
Am I correct in understanding that the formatter is to remain the same and the format is to be added?

2023-12-04 14:29 UTC, unvalley commented on website/prh.yml
> +      - リンタ
> Am I correct in understanding that the formatter is to remain the same and the format is to be added?
Right!

2023-12-05 01:09 UTC, unvalley commented
@yossydev After resolving this
https://github.com/biomejs/biome/pull/986#discussion_r1413934301 it would be good to me.

2023-12-05 11:26 UTC, yossydev commented on .github/workflows/website_deploy_preview.yml
> +        run: pnpm textlint
Sorry! I left it as it was...!

[remove: Run textlint from website deploy ci](https://github.com/biomejs/biome/pull/986/commits/f5dc6027a21634259ce636bde352bad47a26c3b6) ← fixed in

2023-12-05 14:18 UTC, unvalley commented on website/src/content/docs/ja/guides/getting-started.mdx
>  - ファイルのLint
```suggestion
- ファイルのlint
```

2023-12-05 14:19 UTC, unvalley approved these changes
Thank you!

2023-12-05 17:52 UTC, unvalley commented
@nissy-dev please merge this after checking your requested changes🙂

2023-12-06 07:11 UTC, nissy-dev approved these changes
LGTM! Thanks!

2023-12-06 07:11 UTC, merged